/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__sB4RlifM6HkU3x2DNlEMFQ
    tySequence__sB4RlifM6HkU3x2DNlEMFQ;
typedef struct tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content
    tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content;
typedef struct tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw
    tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content
    tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ
    tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content
    tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg
    tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg;
typedef struct tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ
    tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ;
typedef struct tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
struct tySequence__sB4RlifM6HkU3x2DNlEMFQ {
  NI len;
  tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content *p;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len;
  tySequence__4eRCaZmrYLLw2k30GPTiMw_Content *p;
};
struct tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA {
  tySequence__4eRCaZmrYLLw2k30GPTiMw data;
  NI counter;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len;
  tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content *p;
};
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg {
  NI a;
  NI b;
};
struct tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ {
  char dummy;
};
struct tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA {
  NI rc;
  NI rootIdx;
};
struct tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content {
  NI cap;
  tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *data[SEQ_DECL_SIZE];
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
  NI Field0;
  NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content {
  NI cap;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content {
  NI cap;
  NimStringV2 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, f__e_u12)(NimStringV2 *c_p0, NI c_p0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void *a_p0, void *b_p1,
                                                  NI size_p2);
static N_INLINE(int, nimCmpMem)(void *a_p0, void *b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2716)(NimStringV2 *dest_p0,
                                                     NimStringV2 src_p1);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1319)(
    NimStringV2 s_p0, tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg x_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1,
                                                 NI64 b_p2);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2 *s_p0);
N_LIB_PRIVATE
N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2459)(NimStringV2 *s_p0);
static N_INLINE(tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg,
                dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE
N_NIMCALL(void, incl__e_u57)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *s_p0,
                             NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__e_u568)(
    tySequence__sB4RlifM6HkU3x2DNlEMFQ *x_p0,
    tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *y_p1);
N_LIB_PRIVATE N_NIMCALL(void *, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void *p_p0);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, w__e_u636)(void);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__stdZcmdline_u61)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(
    tySequence__sM4lkSb7zS6F7OVMvW9cffQ *x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__stdZcmdline_u55)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3785)(
    tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void *p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___e_u614)(
    tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void *p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void *p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap;
  NIM_CHAR data[3 + 1];
} TM__8VXkWmK9cKS4tHcgIawzmPA_2 = {3 | NIM_STRLIT_FLAG, "   "};
static const NimStringV2 TM__8VXkWmK9cKS4tHcgIawzmPA_3 = {
    3, (NimStrPayload *)&TM__8VXkWmK9cKS4tHcgIawzmPA_2};
static const NimStringV2 TM__8VXkWmK9cKS4tHcgIawzmPA_4 = {
    3, (NimStrPayload *)&TM__8VXkWmK9cKS4tHcgIawzmPA_2};
N_LIB_PRIVATE tySequence__sB4RlifM6HkU3x2DNlEMFQ s__e_u5;
N_LIB_PRIVATE tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA h__e_u11;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static N_INLINE(int, nimCmpMem)(void *a_p0, void *b_p1, NI size_p2) {
  int result;
  result = memcmp(a_p0, b_p1, ((size_t)(size_p2)));
  return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void *a_p0, void *b_p1,
                                                  NI size_p2) {
  NIM_BOOL result;
  int T1_;
  T1_ = (int)0;
  T1_ = nimCmpMem(a_p0, b_p1, size_p2);
  result = (T1_ == ((NI32)0));
  return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
  NIM_BOOL result;
  NI alen_1;
  NI blen_1;
  {
    result = NIM_FALSE;
    alen_1 = a_p0.len;
    blen_1 = b_p1.len;
    {
      if (!(alen_1 == blen_1))
        goto LA3_;
      {
        if (!(alen_1 == ((NI)0)))
          goto LA7_;
        result = NIM_TRUE;
        goto BeforeRet_;
      }
    LA7_:;
      result = equalMem__system_u1749(((void *)((&a_p0.p->data[((NI)0)]))),
                                      ((void *)((&b_p1.p->data[((NI)0)]))),
                                      (alen_1));
      goto BeforeRet_;
    }
  LA3_:;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2 *s_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = !(((*s_p0).p == ((NimStrPayload *)NIM_NIL)));
    if (!(T3_))
      goto LA4_;
    T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) ==
           ((NI)IL64(4611686018427387904)));
  LA4_:;
    if (!T3_)
      goto LA5_;
    nimPrepareStrMutationImpl__system_u2459(s_p0);
  }
LA5_:;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1319)(
    NimStringV2 s_p0, tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg x_p1) {
  NimStringV2 result;
  NI a_1;
  NI L_1;
  NI TM__8VXkWmK9cKS4tHcgIawzmPA_5;
  NI TM__8VXkWmK9cKS4tHcgIawzmPA_6;
  NI TM__8VXkWmK9cKS4tHcgIawzmPA_7;
  {
    result.len = 0;
    result.p = NIM_NIL;
    a_1 = x_p1.a;
    if (nimSubInt(s_p0.len, x_p1.b, &TM__8VXkWmK9cKS4tHcgIawzmPA_5)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimSubInt((NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_5), a_1,
                  &TM__8VXkWmK9cKS4tHcgIawzmPA_6)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimAddInt((NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_6), ((NI)1),
                  &TM__8VXkWmK9cKS4tHcgIawzmPA_7)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    L_1 = (NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_7);
    if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))) {
      raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807)));
      goto BeforeRet_;
    }
    result = mnewString((L_1));
    {
      NI i_1;
      NI i_2;
      i_1 = (NI)0;
      i_2 = ((NI)0);
      {
        while (1) {
          NI TM__8VXkWmK9cKS4tHcgIawzmPA_8;
          NI TM__8VXkWmK9cKS4tHcgIawzmPA_9;
          if (!(i_2 < L_1))
            goto LA3;
          i_1 = i_2;
          if (i_1 < 0 || i_1 >= result.len) {
            raiseIndexError2(i_1, result.len - 1);
            goto BeforeRet_;
          }
          nimPrepareStrMutationV2((&result));
          if (nimAddInt(i_1, a_1, &TM__8VXkWmK9cKS4tHcgIawzmPA_8)) {
            raiseOverflow();
            goto BeforeRet_;
          };
          if ((NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_8) < 0 ||
              (NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_8) >= s_p0.len) {
            raiseIndexError2((NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_8), s_p0.len - 1);
            goto BeforeRet_;
          }
          result.p->data[i_1] =
              s_p0.p->data[(NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_8)];
          if (nimAddInt(i_2, ((NI)1), &TM__8VXkWmK9cKS4tHcgIawzmPA_9)) {
            raiseOverflow();
            goto BeforeRet_;
          };
          i_2 = (NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_9);
        }
      LA3:;
      }
    }
  }
BeforeRet_:;
  return result;
}
static N_INLINE(tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg,
                dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1) {
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg result;
  result.a = a_p0;
  result.b = b_p1;
  return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void, f__e_u12)(NimStringV2 *c_p0, NI c_p0Len_0) {
  NimStringV2 g_1;
  NI __1;
  tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *T13_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    g_1.len = 0;
    g_1.p = NIM_NIL;
    __1 = ((NI)0);
    {
      NimStringV2 *d_1;
      NI i_1;
      d_1 = (NimStringV2 *)0;
      i_1 = ((NI)0);
      {
        while (1) {
          if (!(i_1 < c_p0Len_0))
            goto LA3;
          if (i_1 < 0 || i_1 >= c_p0Len_0) {
            raiseIndexError2(i_1, c_p0Len_0 - 1);
            goto BeforeRet_;
          }
          d_1 = (&c_p0[i_1]);
          {
            NIM_BOOL T6_;
            tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T10_;
            NimStringV2 T11_;
            T6_ = (NIM_BOOL)0;
            T6_ = eqStrings((*d_1), TM__8VXkWmK9cKS4tHcgIawzmPA_3);
            if (T6_)
              goto LA7_;
            T6_ = eqStrings((*d_1), TM__8VXkWmK9cKS4tHcgIawzmPA_4);
          LA7_:;
            if (!T6_)
              goto LA8_;
            T10_ = dotdot___stdZenumutils_u105(((NI)3), ((NI)1));
            T11_.len = 0;
            T11_.p = NIM_NIL;
            T11_ = X5BX5D___pureZstrutils_u1319((*d_1), T10_);
            if (NIM_UNLIKELY(*nimErr_)) {
              eqdestroy___system_u281(T11_);
              goto BeforeRet_;
            }
            eqsink___system_u2716((&g_1), T11_);
          }
          goto LA4_;
        LA8_:;
          {
            incl__e_u57((&h__e_u11), (*d_1));
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
          }
        LA4_:;
          i_1 += ((NI)1);
        }
      LA3:;
      }
    }
    T13_ = NIM_NIL;
    T13_ = (tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *)nimNewObj(
        sizeof(tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ),
        NIM_ALIGNOF(tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ));
    add__e_u568((&s__e_u5), T13_);
    if (g_1.p && !(g_1.p->cap & NIM_STRLIT_FLAG)) {
      deallocShared(g_1.p);
    }
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, w__e_u636)(void) {
  tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result.len = 0;
    result.p = NIM_NIL;
    {
      NI i_1;
      NI colontmp_;
      NI res_1;
      i_1 = (NI)0;
      colontmp_ = (NI)0;
      colontmp_ = paramCount__stdZcmdline_u61();
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      res_1 = ((NI)1);
      {
        while (1) {
          NimStringV2 T4_;
          NI TM__8VXkWmK9cKS4tHcgIawzmPA_10;
          if (!(res_1 <= colontmp_))
            goto LA3;
          i_1 = ((NI)(res_1));
          T4_.len = 0;
          T4_.p = NIM_NIL;
          T4_ = paramStr__stdZcmdline_u55(i_1);
          if (NIM_UNLIKELY(*nimErr_)) {
            eqdestroy___system_u281(T4_);
            goto BeforeRet_;
          }
          add__stdZenumutils_u70((&result), T4_);
          if (nimAddInt(res_1, ((NI)1), &TM__8VXkWmK9cKS4tHcgIawzmPA_10)) {
            raiseOverflow();
            goto BeforeRet_;
          };
          res_1 = (NI)(TM__8VXkWmK9cKS4tHcgIawzmPA_10);
        }
      LA3:;
      }
    }
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
  NI result;
  result = ((NI)((NU)((NU64)(((NU)(x_p0))) - (NU64)(((NU)(y_p1))))));
  return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void *p_p0) {
  NIM_BOOL result;
  result = NIM_FALSE;
  {
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *cell_1;
    NI T5_;
    if (!!((p_p0 == NIM_NIL)))
      goto LA3_;
    T5_ = (NI)0;
    T5_ = minuspercent___system_u813(((NI)(ptrdiff_t)(p_p0)), ((NI)16));
    cell_1 = ((tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *)(T5_));
    {
      if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4))) == ((NI)0)))
        goto LA8_;
      result = NIM_TRUE;
    }
    goto LA6_;
  LA8_:;
    {
      (*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
    }
  LA6_:;
  }
LA3_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___e_u614)(
    tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *dest_p0) {}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___e_u650)(tySequence__sB4RlifM6HkU3x2DNlEMFQ dest_p0) {
  NI colontmp_;
  colontmp_ = ((NI)0);
  {
    while (1) {
      NI T3_;
      T3_ = dest_p0.len;
      if (!(colontmp_ < T3_))
        goto LA2;
      {
        NIM_BOOL T6_;
        T6_ = (NIM_BOOL)0;
        T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
        if (!T6_)
          goto LA7_;
        eqdestroy___e_u614(dest_p0.p->data[colontmp_]);
        nimRawDispose(dest_p0.p->data[colontmp_], ((NI)1));
      }
    LA7_:;
      colontmp_ += ((NI)1);
    }
  LA2:;
  }
  if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
    alignedDealloc(
        dest_p0.p,
        NIM_ALIGNOF(tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *));
  }
}
N_LIB_PRIVATE N_NIMCALL(void, atmedotnim_Init000)(void) {
  {
    tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD_;
    NIM_BOOL *nimErr_;
    nimErr_ = nimErrorFlag();
    colontmpD_.len = 0;
    colontmpD_.p = NIM_NIL;
    colontmpD_ = w__e_u636();
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    f__e_u12(((colontmpD_).p) ? (colontmpD_.p->data) : NIM_NIL, colontmpD_.len);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    eqdestroy___system_u3785(colontmpD_);
  BeforeRet_:;
    nimTestErrorFlag();
  }
}
