/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA
    tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA;
typedef struct tyObject_K__T0CnLg5itDR3hHLPCD9bvdw
    tyObject_K__T0CnLg5itDR3hHLPCD9bvdw;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ
    tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ;
typedef struct tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg
    tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg;
typedef struct tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ
    tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ;
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content *p;
};
struct tyObject_K__T0CnLg5itDR3hHLPCD9bvdw {
  NI kind;
  union {
    struct {
      tyArray__vEOa9c5qaE9ajWxR5R4zwfQg e;
      NU8 r;
    } _kind_2;
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ p;
  };
};
struct tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA {
  NIM_BOOL g;
  union {
    struct {
      tyObject_K__T0CnLg5itDR3hHLPCD9bvdw z;
    } _g_2;
  };
};
struct tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ {
  NIM_BOOL g;
  union {
    struct {
      tySequence__6H5Oh5UUvVCLiakt9aTwtUQ z;
    } _g_2;
  };
};
struct tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ {
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes;
  NI position;
};
struct tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg {
  NIM_BOOL g;
  union {
    struct {
      tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ z;
    } _g_2;
  };
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content {
  NI cap;
  NU8 data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u42)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2) {
  void *T1_;
  T1_ = (void *)0;
  T1_ = memset(a_p0, v_p1, ((size_t)(size_p2)));
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqsink___w_u1286)(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *dest_p0,
                            tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *src_p1) {
  switch ((*dest_p0).g) {
  case NIM_FALSE: {
  } break;
  case NIM_TRUE: {
    switch ((*dest_p0)._g_2.z.kind) {
    case ((NI)2): {
    } break;
    case ((NI)1): {
      (*dest_p0)._g_2.z._kind_2.r = 0;
      nimZeroMem((void *)(*dest_p0)._g_2.z._kind_2.e,
                 sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
    } break;
    case ((NI)0): {
      eqdestroy___w_u42((*dest_p0)._g_2.z.p);
      (*dest_p0)._g_2.z.p.len = 0;
      (*dest_p0)._g_2.z.p.p = NIM_NIL;
    } break;
    default:
      __builtin_unreachable();
    }
    (*dest_p0)._g_2.z.kind = 0;
  } break;
  default: {
  } break;
  }
  (*dest_p0).g = 0;
  (*dest_p0).g = (*src_p1).g;
  switch ((*dest_p0).g) {
  case NIM_FALSE: {
  } break;
  case NIM_TRUE: {
    (*dest_p0)._g_2.z = (*src_p1)._g_2.z;
  } break;
  default: {
  } break;
  }
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1160)(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ *dest_p0) {
  printf("starting eqdestroy___w_u1160: %p\n", (void *)dest_p0);
  switch ((*dest_p0).g) {
  case NIM_FALSE: {
  } break;
  case NIM_TRUE: {
    eqdestroy___w_u42((*dest_p0)._g_2.z);
  } break;
  default: {
  } break;
  }
  printf("finished eqdestroy___w_u1160: %p\n", (void *)dest_p0);
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1113)(tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg *dest_p0) {
  printf("starting eqdestroy___w_u1113: %p\n", (void *)dest_p0);
  switch ((*dest_p0).g) {
  case NIM_FALSE: {
  } break;
  case NIM_TRUE: {
    eqdestroy___w_u42((*dest_p0)._g_2.z.bytes);
  } break;
  default: {
  } break;
  }
  printf("finished eqdestroy___w_u1113: %p\n", (void *)dest_p0);
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1277)(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *dest_p0) {
  printf("starting eqdestroy___w_1277: %p\n", (void *)dest_p0);
  switch ((*dest_p0).g) {
  case NIM_FALSE: {
  } break;
  case NIM_TRUE: {
    switch ((*dest_p0)._g_2.z.kind) {
    case ((NI)2): {
    } break;
    case ((NI)1): {
    } break;
    case ((NI)0): {
      eqdestroy___w_u42((*dest_p0)._g_2.z.p);
    } break;
    default:
      __builtin_unreachable();
    }
  } break;
  default: {
  } break;
  }
  printf("finished eqdestroy___w_1277: %p\n", (void *)dest_p0);
}
