/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ
    tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyTuple__WvmW1wGQccqpiC9aKzOCqZw
    tyTuple__WvmW1wGQccqpiC9aKzOCqZw;
typedef struct tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg
    tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content *p;
};
struct tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ {
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes;
  NI position;
};
struct tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg {
  NI a;
  NI b;
};
struct tyTuple__WvmW1wGQccqpiC9aKzOCqZw {
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg Field0;
  NI Field1;
};
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content {
  NI cap;
  NU8 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE
N_NIMCALL(void, eqcopy___w_u45)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ *dest_p0,
                                tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple__WvmW1wGQccqpiC9aKzOCqZw,
                        k__t_u15)(NU8 *f_p0, NI f_p0Len_0, NI t_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void,
                         raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0);
static N_INLINE(tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg,
                dotdot___t_u19)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__WvmW1wGQccqpiC9aKzOCqZw,
                        item__t_u92)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ,
                        at___t_u165)(NU8 *a_p0, NI a_p0Len_0);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u42)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
static const struct {
  NI cap;
  NIM_CHAR data[0 + 1];
} TM__8i1JnImO9cCb9azUiipl4p4w_2 = {0 | NIM_STRLIT_FLAG, ""};
static const NimStringV2 TM__8i1JnImO9cCb9azUiipl4p4w_3 = {
    0, (NimStrPayload *)&TM__8i1JnImO9cCb9azUiipl4p4w_2};
static const NimStringV2 TM__8i1JnImO9cCb9azUiipl4p4w_4 = {
    0, (NimStrPayload *)&TM__8i1JnImO9cCb9azUiipl4p4w_2};
static const NimStringV2 TM__8i1JnImO9cCb9azUiipl4p4w_5 = {
    0, (NimStrPayload *)&TM__8i1JnImO9cCb9azUiipl4p4w_2};
static const NimStringV2 TM__8i1JnImO9cCb9azUiipl4p4w_8 = {
    0, (NimStrPayload *)&TM__8i1JnImO9cCb9azUiipl4p4w_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
N_LIB_PRIVATE
N_NIMCALL(void, eqcopy___t_u241)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0,
                                 tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ src_p1) {
  eqcopy___w_u45((&(*dest_p0).bytes), src_p1.bytes);
  (*dest_p0).position = src_p1.position;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2) {
  void *T1_;
  T1_ = (void *)0;
  T1_ = memset(a_p0, v_p1, ((size_t)(size_p2)));
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg,
                dotdot___t_u19)(NI a_p0, NI b_p1) {
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg result;
  result.a = a_p0;
  result.b = b_p1;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__WvmW1wGQccqpiC9aKzOCqZw,
                        k__t_u15)(NU8 *f_p0, NI f_p0Len_0, NI t_p1) {
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw result;
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw colontmpD_;
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw colontmpD__2;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result), sizeof(tyTuple__WvmW1wGQccqpiC9aKzOCqZw));
    nimZeroMem((void *)(&colontmpD_), sizeof(tyTuple__WvmW1wGQccqpiC9aKzOCqZw));
    nimZeroMem((void *)(&colontmpD__2),
               sizeof(tyTuple__WvmW1wGQccqpiC9aKzOCqZw));
    {
      if (t_p1 < 0 || t_p1 >= f_p0Len_0) {
        raiseIndexError2(t_p1, f_p0Len_0 - 1);
        goto BeforeRet_;
      }
      if (!((NU8)(f_p0[t_p1]) <= (NU8)(((NU8)127))))
        goto LA3_;
      raiseAssert__stdZassertions_u26(TM__8i1JnImO9cCb9azUiipl4p4w_3);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
    }
    goto LA1_;
  LA3_:;
    {
      if (t_p1 < 0 || t_p1 >= f_p0Len_0) {
        raiseIndexError2(t_p1, f_p0Len_0 - 1);
        goto BeforeRet_;
      }
      if (!((NU8)(f_p0[t_p1]) <= (NU8)(((NU8)183))))
        goto LA6_;
      if (t_p1 < 0 || t_p1 >= f_p0Len_0) {
        raiseIndexError2(t_p1, f_p0Len_0 - 1);
        goto BeforeRet_;
      }
      colontmpD_.Field0 = dotdot___t_u19(
          ((NI)1), ((NI)((NU8)((NU8)(f_p0[t_p1]) - (NU8)(((NU8)128))))));
      colontmpD_.Field1 = ((NI)0);
      result = colontmpD_;
    }
    goto LA1_;
  LA6_:;
    {
      colontmpD__2.Field0 = dotdot___t_u19(((NI)2), ((NI)178));
      colontmpD__2.Field1 = ((NI)0);
      result = colontmpD__2;
    }
  LA1_:;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__WvmW1wGQccqpiC9aKzOCqZw,
                        item__t_u92)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ e_p0) {
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw result;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result), sizeof(tyTuple__WvmW1wGQccqpiC9aKzOCqZw));
    result = k__t_u15(((e_p0.bytes).p) ? (e_p0.bytes.p->data) : NIM_NIL,
                      e_p0.bytes.len, e_p0.position);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ,
                        h__t_u116)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ x_p0) {
  tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ result;
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw m_1;
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg p_1;
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T7_;
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T8_;
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw T9_;
  NI TM__8i1JnImO9cCb9azUiipl4p4w_9;
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T28_;
  NI TM__8i1JnImO9cCb9azUiipl4p4w_10;
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T29_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result), sizeof(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ));
    m_1 = item__t_u92(x_p0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    {
      NI T3_;
      tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T4_;
      T3_ = x_p0.bytes.len;
      T4_ = dotdot___t_u19(m_1.Field0.a, m_1.Field0.b);
      if (!(T3_ <= T4_.b))
        goto LA5_;
      raiseAssert__stdZassertions_u26(TM__8i1JnImO9cCb9azUiipl4p4w_4);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
    }
  LA5_:;
    T7_ = dotdot___t_u19(m_1.Field0.a, m_1.Field0.b);
    T8_ = dotdot___t_u19(m_1.Field0.a, m_1.Field0.b);
    if (T8_.b - T7_.a != -1 && (T7_.a < 0 || T7_.a >= x_p0.bytes.len ||
                                T8_.b < 0 || T8_.b >= x_p0.bytes.len)) {
      raiseIndexError4(T7_.a, T8_.b, x_p0.bytes.len);
      goto BeforeRet_;
    }
    T9_ = k__t_u15(
        (((x_p0.bytes).p) ? ((NU8 *)x_p0.bytes.p->data + (T7_.a)) : NIM_NIL),
        (T8_.b) - (T7_.a) + 1, ((NI)0));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    p_1 = T9_.Field0;
    {
      NI __1;
      NI i_1;
      __1 = (NI)0;
      i_1 = ((NI)0);
      {
        while (1) {
          tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T19_;
          tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T20_;
          tyTuple__WvmW1wGQccqpiC9aKzOCqZw T21_;
          NI TM__8i1JnImO9cCb9azUiipl4p4w_6;
          if (!(i_1 < ((NI)1)))
            goto LA12;
          __1 = i_1;
          {
            NI T15_;
            tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T16_;
            T15_ = x_p0.bytes.len;
            T16_ = dotdot___t_u19(((NI)2), ((NI)178));
            if (!(T15_ <= T16_.b))
              goto LA17_;
            raiseAssert__stdZassertions_u26(TM__8i1JnImO9cCb9azUiipl4p4w_5);
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
          }
        LA17_:;
          T19_ = dotdot___t_u19(((NI)2), ((NI)178));
          T20_ = dotdot___t_u19(((NI)2), ((NI)178));
          if (T20_.b - T19_.a != -1 &&
              (T19_.a < 0 || T19_.a >= x_p0.bytes.len || T20_.b < 0 ||
               T20_.b >= x_p0.bytes.len)) {
            raiseIndexError4(T19_.a, T20_.b, x_p0.bytes.len);
            goto BeforeRet_;
          }
          T21_ = k__t_u15((((x_p0.bytes).p)
                               ? ((NU8 *)x_p0.bytes.p->data + (T19_.a))
                               : NIM_NIL),
                          (T20_.b) - (T19_.a) + 1, ((NI)0));
          if (NIM_UNLIKELY(*nimErr_))
            goto BeforeRet_;
          p_1 = T21_.Field0;
          if (nimAddInt(i_1, ((NI)1), &TM__8i1JnImO9cCb9azUiipl4p4w_6)) {
            raiseOverflow();
            goto BeforeRet_;
          };
          i_1 = (NI)(TM__8i1JnImO9cCb9azUiipl4p4w_6);
        }
      LA12:;
      }
    }
    {
      NI T24_;
      NI TM__8i1JnImO9cCb9azUiipl4p4w_7;
      tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg T25_;
      T24_ = x_p0.bytes.len;
      if (nimAddInt(((NI)2), p_1.b, &TM__8i1JnImO9cCb9azUiipl4p4w_7)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      T25_ = dotdot___t_u19(((NI)2), (NI)(TM__8i1JnImO9cCb9azUiipl4p4w_7));
      if (!(T24_ <= T25_.b))
        goto LA26_;
      raiseAssert__stdZassertions_u26(TM__8i1JnImO9cCb9azUiipl4p4w_8);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
    }
  LA26_:;
    if (nimAddInt(((NI)2), p_1.b, &TM__8i1JnImO9cCb9azUiipl4p4w_9)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T28_ = dotdot___t_u19(((NI)2), (NI)(TM__8i1JnImO9cCb9azUiipl4p4w_9));
    if (nimAddInt(((NI)2), p_1.b, &TM__8i1JnImO9cCb9azUiipl4p4w_10)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T29_ = dotdot___t_u19(((NI)2), (NI)(TM__8i1JnImO9cCb9azUiipl4p4w_10));
    if (T29_.b - T28_.a != -1 && (T28_.a < 0 || T28_.a >= x_p0.bytes.len ||
                                  T29_.b < 0 || T29_.b >= x_p0.bytes.len)) {
      raiseIndexError4(T28_.a, T29_.b, x_p0.bytes.len);
      goto BeforeRet_;
    }
    result.bytes = at___t_u165(
        (((x_p0.bytes).p) ? ((NU8 *)x_p0.bytes.p->data + (T28_.a)) : NIM_NIL),
        (T29_.b) - (T28_.a) + 1);
    result.position = ((NI)0);
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___t_u238)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0) {
  eqdestroy___w_u42((*dest_p0).bytes);
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___t_u235)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0) {
  (*dest_p0).bytes.len = 0;
  (*dest_p0).bytes.p = NIM_NIL;
  (*dest_p0).position = 0;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL,
                        j__t_u113)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ v_p0) {
  NIM_BOOL result;
  {
    if (v_p0.position < 0 || v_p0.position >= v_p0.bytes.len) {
      raiseIndexError2(v_p0.position, v_p0.bytes.len - 1);
      goto BeforeRet_;
    }
    result = ((NU8)(((NU8)192)) <= (NU8)(v_p0.bytes.p->data[v_p0.position]));
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void, eqsink___t_u247)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0,
                                 tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ src_p1) {
  if ((*dest_p0).bytes.p != src_p1.bytes.p) {
    eqdestroy___w_u42((*dest_p0).bytes);
  }
  (*dest_p0).bytes.len = src_p1.bytes.len;
  (*dest_p0).bytes.p = src_p1.bytes.p;
  (*dest_p0).position = src_p1.position;
}
