/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Table__VXRlZVRc73Y2yFgFbVYXng
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og
    tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content
    tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg
    tySequence__aLjCOs9bu5l2rz6ENM6m6Sg;
typedef struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content
    tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg;
typedef struct tyObject_K__T0CnLg5itDR3hHLPCD9bvdw
    tyObject_K__T0CnLg5itDR3hHLPCD9bvdw;
typedef struct tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA
    tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA;
typedef struct tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ
    tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA;
typedef struct tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg
    tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg;
typedef struct tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw
    tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q
    tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA
    tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA;
typedef struct tyTuple__n2s9chmKZxsUwRqu6DJsQeg
    tyTuple__n2s9chmKZxsUwRqu6DJsQeg;
typedef struct tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw
    tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw;
typedef struct tySequence__gTwrrlHWmZAujkkSb6c2Wg
    tySequence__gTwrrlHWmZAujkkSb6c2Wg;
typedef struct tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content
    tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content;
typedef struct tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg
    tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg;
typedef struct tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ
    tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ;
typedef struct tyTuple__WvmW1wGQccqpiC9aKzOCqZw
    tyTuple__WvmW1wGQccqpiC9aKzOCqZw;
typedef struct tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg
    tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__589aIoFuYV9awMG68GXzrKTA
    tySequence__589aIoFuYV9awMG68GXzrKTA;
typedef struct tySequence__589aIoFuYV9awMG68GXzrKTA_Content
    tySequence__589aIoFuYV9awMG68GXzrKTA_Content;
typedef struct tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw
    tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content
    tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tySequence__sB4RlifM6HkU3x2DNlEMFQ
    tySequence__sB4RlifM6HkU3x2DNlEMFQ;
typedef struct tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content
    tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ
    tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple__PCiVg29bAs9cXcHeoQrt1xeA
    tyTuple__PCiVg29bAs9cXcHeoQrt1xeA;
typedef struct tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ
    tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ
    tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ;
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len;
  tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content *p;
};
struct tyObject_Table__VXRlZVRc73Y2yFgFbVYXng {
  tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
  NI counter;
};
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg {
  NI len;
  tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content *p;
};
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
  NimStringV2 Field0;
  NI Field1;
};
typedef tyTuple__XOVT24GHXwqiEj5GCsEGCA tyArray__OD9bY6QVEXZn9aOq56is5sPQ[1];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content *p;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tyObject_K__T0CnLg5itDR3hHLPCD9bvdw {
  NI kind;
  union {
    struct {
      tyArray__vEOa9c5qaE9ajWxR5R4zwfQg e;
      NU8 r;
    } _kind_2;
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ p;
  };
};
struct tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA {
  NIM_BOOL g;
  union {
    struct {
      tyObject_K__T0CnLg5itDR3hHLPCD9bvdw z;
    } _g_2;
  };
};
struct tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ {
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes;
  NI position;
};
struct tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg {
  tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *v;
};
struct tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA {
  NI rc;
  NI rootIdx;
};
struct TNimTypeV2 {
  void *destructor;
  NI size;
  NI16 align;
  NI16 depth;
  NU32 *display;
  void *traceImpl;
  void *typeInfoV1;
  NI flags;
  void *vTable[SEQ_DECL_SIZE];
};
struct tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw {
  NI len;
  NI cap;
  tyTuple__N4J9cV4JZGem3ljqqj5rT0Q *d;
};
struct tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA {
  NI len;
  NI cap;
  tyTuple__n2s9chmKZxsUwRqu6DJsQeg *d;
};
struct tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg {
  tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw traceStack;
  tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA toFree;
  NI freed;
  NI touched;
  NI edges;
  NI rcSum;
  NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
  void **Field0;
  TNimTypeV2 *Field1;
};
struct tySequence__gTwrrlHWmZAujkkSb6c2Wg {
  NI len;
  tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content *p;
};
struct tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw {
  tySequence__gTwrrlHWmZAujkkSb6c2Wg data;
  NI counter;
};
typedef NU8 tyArray__ekVvh9bp9cVe7STNUL8R406w[1];
struct tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg {
  NIM_BOOL g;
  union {
    struct {
      tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ z;
    } _g_2;
  };
};
struct tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ {
  NIM_BOOL g;
  union {
    struct {
      tySequence__6H5Oh5UUvVCLiakt9aTwtUQ z;
    } _g_2;
  };
};
struct tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg {
  NI a;
  NI b;
};
struct tyTuple__WvmW1wGQccqpiC9aKzOCqZw {
  tyObject_HSlice__UvO09cfq3M4qF9ccZcn8eXpg Field0;
  NI Field1;
};
struct RootObj {
  TNimTypeV2 *m_type;
};
struct tySequence__589aIoFuYV9awMG68GXzrKTA {
  NI len;
  tySequence__589aIoFuYV9awMG68GXzrKTA_Content *p;
};
struct Exception {
  RootObj Sup;
  Exception *parent;
  NCSTRING name;
  NimStringV2 message;
  tySequence__589aIoFuYV9awMG68GXzrKTA trace;
  Exception *up;
};
typedef struct {
  NU8 *Field0;
  NI Field1;
} tyOpenArray__UMVJID9bgFAzHOc9bt5jE4PA;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len;
  tySequence__4eRCaZmrYLLw2k30GPTiMw_Content *p;
};
struct tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA {
  tySequence__4eRCaZmrYLLw2k30GPTiMw data;
  NI counter;
};
struct tySequence__sB4RlifM6HkU3x2DNlEMFQ {
  NI len;
  tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content *p;
};
struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
  NI Field0;
  NimStringV2 Field1;
  NI Field2;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content {
  NI cap;
  tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content {
  NI cap;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data[SEQ_DECL_SIZE];
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content {
  NI cap;
  NU8 data[SEQ_DECL_SIZE];
};
struct tyTuple__PCiVg29bAs9cXcHeoQrt1xeA {
  NI Field0;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ Field1;
  NI Field2;
};
struct tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content {
  NI cap;
  tyTuple__PCiVg29bAs9cXcHeoQrt1xeA data[SEQ_DECL_SIZE];
};
struct tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ {
  NCSTRING procname;
  NI line;
  NCSTRING filename;
};
struct tySequence__589aIoFuYV9awMG68GXzrKTA_Content {
  NI cap;
  tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ data[SEQ_DECL_SIZE];
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
  NI Field0;
  NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content {
  NI cap;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__sB4RlifM6HkU3x2DNlEMFQ_Content {
  NI cap;
  tyObject_WcolonObjectType___qW9baI3FVjn1q7oAe9biuOoQ *data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE
    N_NIMCALL(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng,
              toTable__w_u1365)(tyTuple__XOVT24GHXwqiEj5GCsEGCA *pairs_p0,
                                NI pairs_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void,
                        v__w_u1350)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ g_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *,
                        new__w_u1353)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void *p_p0,
                                                       TNimTypeV2 *desc_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3482)(
    NIM_BOOL isDestroyAction_p0,
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *s_p1, TNimTypeV2 *desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__w_u2958)(void *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u940)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void *p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___w_u952)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *dest_p0, void *env_p1);
static N_INLINE(void, nimTraceRef)(void *q_p0, TNimTypeV2 *desc_p1,
                                   void *env_p2);
static N_INLINE(void, add__system_u3022)(
    tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw *s_p0, void **c_p1,
    TNimTypeV2 *t_p2);
N_LIB_PRIVATE
N_NIMCALL(void,
          resize__system_u3030)(tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw *s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE
N_NIMCALL(void,
          x__w_u290)(tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg **t_p0,
                     NU8 *g_p1, NI g_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ,
                        at___t_u165)(NU8 *a_p0, NI a_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, getOrDefault__w_u375)(
    tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw t_p0,
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___w_u923)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg **dest_p0,
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *src_p1,
    NIM_BOOL cyclic_p2);
static N_INLINE(void, nimIncRefCyclic)(void *p_p0, NIM_BOOL cyclic_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u899)(
    tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u42)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqsink___w_u1286)(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *dest_p0,
                            tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *src_p1);
N_LIB_PRIVATE
N_NIMCALL(void, p__w_u1232)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ f_p0, NU8 i_p1,
                            tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *Result);
N_LIB_PRIVATE
N_NIMCALL(void, eqcopy___t_u241)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0,
                                 tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ,
                        n__w_u1138)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ d_p0);
N_LIB_PRIVATE N_NIMCALL(tyTuple__WvmW1wGQccqpiC9aKzOCqZw,
                        item__t_u92)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ e_p0);
N_LIB_PRIVATE N_NOINLINE(void,
                         raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2 *source_p0,
                                             NI16 targetDepth_p1,
                                             NU32 token_p2);
static N_INLINE(Exception *, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void,
                        eqcopy___stdZtypedthreads_u223)(Exception **dest_p0,
                                                        Exception *src_p1,
                                                        NIM_BOOL cyclic_p2);
N_LIB_PRIVATE
N_NIMCALL(void, s__w_u1103)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ f_p0,
                            tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg *Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ,
                        h__t_u116)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ x_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___t_u238)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1160)(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1113)(tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg *dest_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringV2 f_p0,
                                                 NI discVal_p1);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___t_u235)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL,
                        j__t_u113)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ v_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ,
                        m__w_u1190)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ w_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ,
                        newSeq__t_u195)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1,
                                                 NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___w_u39)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void, eqsink___t_u247)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ *dest_p0,
                                 tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void,
                        w__w_u1230)(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ,
                        u__w_u1344)(NU8 *data_p0, NI data_p0Len_0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___w_u1312)(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1277)(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1315)(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u920)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg, y__w_u4)(void);
N_LIB_PRIVATE N_NIMCALL(void *, newSeqPayload)(NI cap_p0, NI elemSize_p1,
                                               NI elemAlign_p2);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u21)(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1529)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___e_u775)(
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___e_u650)(tySequence__sB4RlifM6HkU3x2DNlEMFQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmedotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap;
  NIM_CHAR data[0 + 1];
} TM__uos5llwHv3fXsxhC8qvS9cw_3 = {0 | NIM_STRLIT_FLAG, ""};
N_LIB_PRIVATE TNimTypeV2 NTIv2__qRQIF8n6ULu1H5MHwOhPIg_;
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_5 = {
    0, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_3};
static const struct {
  NI cap;
  NIM_CHAR data[52 + 1];
} TM__uos5llwHv3fXsxhC8qvS9cw_6 = {
    52 | NIM_STRLIT_FLAG,
    "field \'z\' is not accessible for type \'Q\' using \'g = "};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_7 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_8 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_9 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_10 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_11 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_12 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_13 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_14 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_15 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_16 = {
    52, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_6};
static const struct {
  NI cap;
  NIM_CHAR data[55 + 1];
} TM__uos5llwHv3fXsxhC8qvS9cw_17 = {
    55 | NIM_STRLIT_FLAG,
    "field \'r\' is not accessible for type \'K\' using \'kind = "};
static const NimStringV2 TM__uos5llwHv3fXsxhC8qvS9cw_18 = {
    55, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_17};
static NIM_CONST tyArray__OD9bY6QVEXZn9aOq56is5sPQ
    TM__uos5llwHv3fXsxhC8qvS9cw_2 = {
        {{0, (NimStrPayload *)&TM__uos5llwHv3fXsxhC8qvS9cw_3}, ((NI)0)}};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static NIM_CONST NU32 TM__uos5llwHv3fXsxhC8qvS9cw_4[1] = {336074496};
N_LIB_PRIVATE TNimTypeV2 NTIv2__qRQIF8n6ULu1H5MHwOhPIg_ = {
    .destructor = (void *)rttiDestroy__w_u2958,
    .size = sizeof(tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg),
    .align =
        (NI16)NIM_ALIGNOF(tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg),
    .depth = 0,
    .display = TM__uos5llwHv3fXsxhC8qvS9cw_4,
    .traceImpl = (void *)eqtrace___w_u952,
    .flags = 0};
extern NIM_THREADVAR Exception *currException__system_u4070;
extern tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA h__e_u11;
extern tySequence__sB4RlifM6HkU3x2DNlEMFQ s__e_u5;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2) {
  void *T1_;
  T1_ = (void *)0;
  T1_ = memset(a_p0, v_p1, ((size_t)(size_p2)));
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
  NI result;
  result = ((NI)((NU)((NU64)(((NU)(x_p0))) - (NU64)(((NU)(y_p1))))));
  return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void *p_p0,
                                                       TNimTypeV2 *desc_p1) {
  NIM_BOOL result;
  result = NIM_FALSE;
  {
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *cell_1;
    NI T5_;
    if (!!((p_p0 == NIM_NIL)))
      goto LA3_;
    T5_ = (NI)0;
    T5_ = minuspercent___system_u813(((NI)(ptrdiff_t)(p_p0)), ((NI)16));
    cell_1 = ((tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *)(T5_));
    {
      if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0)))
        goto LA8_;
      result = NIM_TRUE;
    }
    goto LA6_;
  LA8_:;
    {
      (*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
    }
  LA6_:;
    rememberCycle__system_u3482(result, cell_1, desc_p1);
  }
LA3_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u940)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *dest_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicStatic(
        (*dest_p0).v, ((TNimTypeV2 *)((&NTIv2__qRQIF8n6ULu1H5MHwOhPIg_))));
    if (!T3_)
      goto LA4_;
    eqdestroy___w_u940((*dest_p0).v);
    nimRawDispose((*dest_p0).v, ((NI)8));
  }
LA4_:;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__w_u2958)(void *dest_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    eqdestroy___w_u940(
        ((tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *)(dest_p0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
  NI result;
  result = ((NI)((NU)((NU64)(((NU)(x_p0))) + (NU64)(((NU)(y_p1))))));
  return result;
}
static N_INLINE(void, add__system_u3022)(
    tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw *s_p0, void **c_p1,
    TNimTypeV2 *t_p2) {
  void **colontmp_;
  TNimTypeV2 *colontmp__2;
  {
    if (!((*s_p0).cap <= (*s_p0).len))
      goto LA3_;
    resize__system_u3030(s_p0);
  }
LA3_:;
  colontmp_ = c_p1;
  colontmp__2 = t_p2;
  (*s_p0).d[(*s_p0).len].Field0 = colontmp_;
  (*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
  (*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRef)(void *q_p0, TNimTypeV2 *desc_p1,
                                   void *env_p2) {
  void **p_1;
  p_1 = ((void **)(q_p0));
  {
    tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg *j_1;
    if (!!(((*p_1) == NIM_NIL)))
      goto LA3_;
    j_1 = ((tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg *)(env_p2));
    add__system_u3022((&(*j_1).traceStack), p_1, desc_p1);
  }
LA3_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___w_u952)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *dest_p0, void *env_p1) {
  nimTraceRef(&(*dest_p0).v,
              ((TNimTypeV2 *)((&NTIv2__qRQIF8n6ULu1H5MHwOhPIg_))), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u920)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *dest_p0) {
  printf("starting eqdestroy___w_u920: %p\n", (void *)dest_p0);
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicStatic(
        dest_p0, ((TNimTypeV2 *)((&NTIv2__qRQIF8n6ULu1H5MHwOhPIg_))));
    if (!T3_)
      goto LA4_;
    eqdestroy___w_u940(dest_p0);
    nimRawDispose(dest_p0, ((NI)8));
  }
LA4_:;
  printf("finished eqdestroy___w_u920: %p\n", (void *)dest_p0);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___w_u917)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg **dest_p0) {
  (*dest_p0) = 0;
}
static N_INLINE(void, nimIncRefCyclic)(void *p_p0, NIM_BOOL cyclic_p1) {
  tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *h_1;
  NI T1_;
  T1_ = (NI)0;
  T1_ = minuspercent___system_u813(((NI)(ptrdiff_t)(p_p0)), ((NI)16));
  h_1 = ((tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *)(T1_));
  (*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___w_u923)(
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg **dest_p0,
    tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *src_p1,
    NIM_BOOL cyclic_p2) {
  tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *colontmp_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    colontmp_ = (*dest_p0);
    {
      if (!src_p1)
        goto LA3_;
      nimIncRefCyclic(src_p1, cyclic_p2);
    }
  LA3_:;
    (*dest_p0) = src_p1;
    {
      NIM_BOOL T7_;
      T7_ = (NIM_BOOL)0;
      T7_ = nimDecRefIsLastCyclicStatic(
          colontmp_, ((TNimTypeV2 *)((&NTIv2__qRQIF8n6ULu1H5MHwOhPIg_))));
      if (!T7_)
        goto LA8_;
      eqdestroy___w_u940(colontmp_);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      nimRawDispose(colontmp_, ((NI)8));
    }
  LA8_:;
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          x__w_u290)(tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg **t_p0,
                     NU8 *g_p1, NI g_p1Len_0) {
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ g_2;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    g_2.len = 0;
    g_2.p = NIM_NIL;
    g_2 = at___t_u165(g_p1, g_p1Len_0);
    {
      while (1) {
        tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw colontmpD_;
        NI T3_;
        if (!!(((*t_p0) ==
                ((tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *)
                     NIM_NIL))))
          goto LA2;
        nimZeroMem((void *)(&colontmpD_),
                   sizeof(tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw));
        nimZeroMem((void *)(&colontmpD_),
                   sizeof(tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw));
        T3_ = (NI)0;
        T3_ = getOrDefault__w_u375(colontmpD_, g_2);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        (void)(T3_);
        eqcopy___w_u923(&(*t_p0), (*(*t_p0)).v, NIM_TRUE);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        eqdestroy___w_u899((&colontmpD_));
      }
    LA2:;
    }
    eqdestroy___w_u42(g_2);
  }
BeforeRet_:;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2 *source_p0,
                                             NI16 targetDepth_p1,
                                             NU32 token_p2) {
  NIM_BOOL result;
  NIM_BOOL T1_;
  T1_ = (NIM_BOOL)0;
  T1_ = (targetDepth_p1 <= (*source_p0).depth);
  if (!(T1_))
    goto LA2_;
  T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_:;
  result = T1_;
  return result;
}
static N_INLINE(Exception *, nimBorrowCurrentException)(void) {
  Exception *result;
  result = currException__system_u4070;
  return result;
}
static N_INLINE(void, popCurrentException)(void) {
  eqcopy___stdZtypedthreads_u223(&currException__system_u4070,
                                 (*currException__system_u4070).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ,
                        n__w_u1138)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ d_p0) {
  tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ result;
  tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ T2_;
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw T9_;
  tyTuple__WvmW1wGQccqpiC9aKzOCqZw T10_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result), sizeof(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ));
    result.g = NIM_TRUE;
    {
      NI T5_;
      tyTuple__WvmW1wGQccqpiC9aKzOCqZw T6_;
      T5_ = d_p0.bytes.len;
      T6_ = item__t_u92(d_p0);
      if (NIM_UNLIKELY(*nimErr_))
        goto LA1_;
      if (!(T5_ <= T6_.Field0.b))
        goto LA7_;
      raiseAssert__stdZassertions_u26(TM__uos5llwHv3fXsxhC8qvS9cw_5);
      if (NIM_UNLIKELY(*nimErr_))
        goto LA1_;
    }
  LA7_:;
    T9_ = item__t_u92(d_p0);
    if (NIM_UNLIKELY(*nimErr_))
      goto LA1_;
    T10_ = item__t_u92(d_p0);
    if (NIM_UNLIKELY(*nimErr_))
      goto LA1_;
    if (T10_.Field0.b - T9_.Field0.a != -1 &&
        (T9_.Field0.a < 0 || T9_.Field0.a >= d_p0.bytes.len ||
         T10_.Field0.b < 0 || T10_.Field0.b >= d_p0.bytes.len)) {
      raiseIndexError4(T9_.Field0.a, T10_.Field0.b, d_p0.bytes.len);
      goto LA1_;
    }
    result._g_2.z = at___t_u165(
        (((d_p0.bytes).p) ? ((NU8 *)d_p0.bytes.p->data + (T9_.Field0.a))
                          : NIM_NIL),
        (T10_.Field0.b) - (T9_.Field0.a) + 1);
    if (NIM_UNLIKELY(*nimErr_)) {
    LA1_:;
      if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2,
                            2015309056)) {
        *nimErr_ = NIM_FALSE;
        nimZeroMem((void *)(&result),
                   sizeof(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ));
        result.g = NIM_FALSE;
        popCurrentException();
      LA12_:;
      }
    }
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void, s__w_u1103)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ f_p0,
                            tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg *Result) {
  tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ T1_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)Result, sizeof(tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg));
    (*Result).g = NIM_TRUE;
    nimZeroMem((void *)(&T1_), sizeof(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ));
    T1_ = h__t_u116(f_p0);
    if (NIM_UNLIKELY(*nimErr_)) {
      eqdestroy___t_u238(&T1_);
      goto BeforeRet_;
    }
    (*Result)._g_2.z = T1_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ,
                        m__w_u1190)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ w_p0) {
  tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ result;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ resultX60gensym7__1;
  tyOpenArray__UMVJID9bgFAzHOc9bt5jE4PA T1_;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_1;
  {
    nimZeroMem((void *)(&result), sizeof(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ));
    resultX60gensym7__1.len = 0;
    resultX60gensym7__1.p = NIM_NIL;
    result.g = NIM_TRUE;
    if (((NI)1) - w_p0.position != -1 &&
        (w_p0.position < 0 || w_p0.position >= w_p0.bytes.len || ((NI)1) < 0 ||
         ((NI)1) >= w_p0.bytes.len)) {
      raiseIndexError4(w_p0.position, ((NI)1), w_p0.bytes.len);
      goto BeforeRet_;
    }
    if ((((((NI)1)) - (w_p0.position) + 1)) < ((NI)0) ||
        (((((NI)1)) - (w_p0.position) + 1)) > ((NI)IL64(9223372036854775807))) {
      raiseRangeErrorI(((((NI)1)) - (w_p0.position) + 1), ((NI)0),
                       ((NI)IL64(9223372036854775807)));
      goto BeforeRet_;
    }
    resultX60gensym7__1 = newSeq__t_u195((((((NI)1)) - (w_p0.position) + 1)));
    if (((NI)1) - w_p0.position != -1 &&
        (w_p0.position < 0 || w_p0.position >= w_p0.bytes.len || ((NI)1) < 0 ||
         ((NI)1) >= w_p0.bytes.len)) {
      raiseIndexError4(w_p0.position, ((NI)1), w_p0.bytes.len);
      goto BeforeRet_;
    }
    T1_.Field0 =
        (((w_p0.bytes).p) ? ((NU8 *)w_p0.bytes.p->data + (w_p0.position))
                          : NIM_NIL);
    T1_.Field1 = (((NI)1)) - (w_p0.position) + 1;
    if (((NI)0) < 0 || ((NI)0) >= T1_.Field1) {
      raiseIndexError2(((NI)0), T1_.Field1 - 1);
      goto BeforeRet_;
    }
    (void)(T1_.Field0[((NI)0)]);
    blitTmp_1 = resultX60gensym7__1;
    result._g_2.z = blitTmp_1;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void,
                        w__w_u1230)(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result) {
  nimZeroMem((void *)Result, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
}
N_LIB_PRIVATE
N_NIMCALL(void, p__w_u1232)(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ f_p0, NU8 i_p1,
                            tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA *Result) {
  printf("starting p__w_u1232\n");
  tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ w_1;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)Result, sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
    nimZeroMem((void *)(&w_1), sizeof(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ));
    eqcopy___t_u241((&w_1), f_p0);
    {
      while (1) {
        {
          tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg wX60gensym8__1;
          tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ colontmpD_;
          tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ colontmpD__2;
          tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ T9_;
          if (!(i_p1 == ((NU8)0)))
            goto LA6_;
          nimZeroMem((void *)(&wX60gensym8__1),
                     sizeof(tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg));
          nimZeroMem((void *)(&colontmpD_),
                     sizeof(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ));
          nimZeroMem((void *)(&colontmpD__2),
                     sizeof(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ));
          s__w_u1103(w_1, (&wX60gensym8__1));
          if (NIM_UNLIKELY(*nimErr_))
            goto LA8_;
          switch (wX60gensym8__1.g) {
          case NIM_FALSE: {
            tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA T11_;
            nimZeroMem((void *)(&T11_),
                       sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
            eqsink___w_u1286(Result, (&T11_));
            eqdestroy___w_u1160((&colontmpD__2));
            eqdestroy___t_u238((&colontmpD_));
            eqdestroy___w_u1113((&wX60gensym8__1));
            eqdestroy___t_u238((&w_1));
            goto BeforeRet_;
          } break;
          case NIM_TRUE: {
            if (!(((2 & ((NU8)1 << ((NU)((wX60gensym8__1.g)) & 7U))) != 0))) {
              raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_7,
                               (NI)(wX60gensym8__1.g));
              goto LA8_;
            }
            colontmpD_ = wX60gensym8__1._g_2.z;
            if (!(((2 & ((NU8)1 << ((NU)((wX60gensym8__1.g)) & 7U))) != 0))) {
              raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_8,
                               (NI)(wX60gensym8__1.g));
              goto LA8_;
            }
            eqwasMoved___t_u235((&wX60gensym8__1._g_2.z));
            T9_ = colontmpD_;
          } break;
          default: {
          } break;
          }
          colontmpD__2 = n__w_u1138(T9_);
          if (NIM_UNLIKELY(*nimErr_))
            goto LA8_;
          (void)(colontmpD__2);
          (*Result).g = NIM_TRUE;
          nimZeroMem((void *)(&(*Result)._g_2.z),
                     sizeof(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw));
          (*Result)._g_2.z.kind = ((NI)0);
          (*Result)._g_2.z.p.len = 0;
          (*Result)._g_2.z.p.p = NIM_NIL;
          eqdestroy___w_u1160((&colontmpD__2));
          eqdestroy___t_u238((&colontmpD_));
          eqdestroy___w_u1113((&wX60gensym8__1));
          eqdestroy___t_u238((&w_1));
          goto BeforeRet_;
          {
          LA8_:;
          }
          {
            eqdestroy___w_u1160((&colontmpD__2));
            eqdestroy___t_u238((&colontmpD_));
            eqdestroy___w_u1113((&wX60gensym8__1));
          }
          if (NIM_UNLIKELY(*nimErr_))
            goto LA1_;
        }
        goto LA4_;
      LA6_:;
        {
          tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ h_1;
          printf("h_1 and wX60gensym9__1 come into scope; &h_1 = %p\n", (void *)(&h_1));
          tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg wX60gensym9__1;
          tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ T18_;
          nimZeroMem((void *)(&h_1),
                     sizeof(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ));
          printf("nimZeroMem'd &h_1 and &wX60gensym9__1\n");
          nimZeroMem((void *)(&wX60gensym9__1),
                     sizeof(tyObject_Q__ru9a7IlHdS3stWvHcyQ89chg));
          s__w_u1103(w_1, (&wX60gensym9__1));
	  printf("called s__w_u1103(w_1, (&wX60gensym9__1));\n");
          if (NIM_UNLIKELY(*nimErr_))
            goto LA17_;
          switch (wX60gensym9__1.g) {
          case NIM_FALSE: {
            tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA T20_;
            nimZeroMem((void *)(&T20_),
                       sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
            eqsink___w_u1286(Result, (&T20_));
            eqdestroy___w_u1113((&wX60gensym9__1));
            printf("calling eqdestroy___t_u238((&h_1));\n");
            eqdestroy___t_u238((&h_1));
            printf("called eqdestroy___t_u238((&h_1));\n");
            eqdestroy___t_u238((&w_1));
            goto BeforeRet_;
          } break;
          case NIM_TRUE: {
            if (!(((2 & ((NU8)1 << ((NU)((wX60gensym9__1.g)) & 7U))) != 0))) {
              raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_9,
                               (NI)(wX60gensym9__1.g));
              goto LA17_;
            }
            printf("assigning h_1 = wX60gensym9__1._g_2.z;\n");
            h_1 = wX60gensym9__1._g_2.z;
            printf("assigned h_1 = wX60gensym9__1._g_2.z;\n");
            if (!(((2 & ((NU8)1 << ((NU)((wX60gensym9__1.g)) & 7U))) != 0))) {
              raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_10,
                               (NI)(wX60gensym9__1.g));
              goto LA17_;
            }
            eqwasMoved___t_u235((&wX60gensym9__1._g_2.z));
          } break;
          default: {
          } break;
          }
          {
            NIM_BOOL T25_;
            tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ wX60gensym11__1;
            tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD__3;
            T25_ = (NIM_BOOL)0;
	    printf("calling j__t_u113(h_1); read-only, idempotent\n");
            T25_ = j__t_u113(h_1);
	    printf("called j__t_u113(h_1); read-only, idempotent\n");
            if (NIM_UNLIKELY(*nimErr_))
              goto LA17_;
            if (!T25_)
              goto LA26_;
            nimZeroMem((void *)(&wX60gensym11__1),
                       sizeof(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ));
            colontmpD__3.len = 0;
            colontmpD__3.p = NIM_NIL;
            {
              NI T31_;
              tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T32_;
	      printf("calling m__w_u_u1190(h_1); (looks irrelevant)\n");
              wX60gensym11__1 = m__w_u1190(h_1);
	      printf("calling m__w_u_u1190(h_1); (looks irrelevant)\n");
              if (NIM_UNLIKELY(*nimErr_))
                goto LA28_;
              T32_.len = 0;
              T32_.p = NIM_NIL;
              switch (wX60gensym11__1.g) {
              case NIM_FALSE: {
                tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA T34_;
                nimZeroMem((void *)(&T34_),
                           sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
                eqsink___w_u1286(Result, (&T34_));
                eqdestroy___w_u42(colontmpD__3);
                eqdestroy___w_u1160((&wX60gensym11__1));
                eqdestroy___w_u1113((&wX60gensym9__1));
                printf("calling eqdestroy___t_u238((&h_1));");
                eqdestroy___t_u238((&h_1));
                printf("called eqdestroy___t_u238((&h_1));");
                eqdestroy___t_u238((&w_1));
                goto BeforeRet_;
              } break;
              case NIM_TRUE: {
                if (!(((2 & ((NU8)1 << ((NU)((wX60gensym11__1.g)) & 7U))) !=
                       0))) {
                  raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_11,
                                   (NI)(wX60gensym11__1.g));
                  goto LA28_;
                }
                colontmpD__3 = wX60gensym11__1._g_2.z;
                if (!(((2 & ((NU8)1 << ((NU)((wX60gensym11__1.g)) & 7U))) !=
                       0))) {
                  raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_12,
                                   (NI)(wX60gensym11__1.g));
                  goto LA28_;
                }
                eqwasMoved___w_u39((&wX60gensym11__1._g_2.z));
                T32_ = colontmpD__3;
              } break;
              default: {
              } break;
              }
              T31_ = T32_.len;
              if (!(((NI)32) < T31_))
                goto LA37_;
              nimZeroMem((void *)Result,
                         sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
              eqdestroy___w_u42(colontmpD__3);
              eqdestroy___w_u1160((&wX60gensym11__1));
              eqdestroy___w_u1113((&wX60gensym9__1));
              printf("calling eqdestroy___t_u238((&h_1));");
              eqdestroy___t_u238((&h_1));
              printf("called eqdestroy___t_u238((&h_1));");
              eqdestroy___t_u238((&w_1));
              goto BeforeRet_;
            }
            goto LA29_;
          LA37_:;
            {
              printf("calling eqsink___t_u247 and eqWasMoved___t_u235 on h_1\n");
              eqsink___t_u247((&w_1), h_1);
              eqwasMoved___t_u235((&h_1));
              printf("called eqsink___t_u247 and eqWasMoved___t_u235 on h_1\n");
            }
          LA29_:;
            {
            LA28_:;
            }
            {
              eqdestroy___w_u42(colontmpD__3);
              eqdestroy___w_u1160((&wX60gensym11__1));
            }
            if (NIM_UNLIKELY(*nimErr_))
              goto LA17_;
          }
          goto LA23_;
        LA26_:;
          {
            tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ wX60gensym12__1;
            tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD__4;
            NI d_1;
            NI T44_;
            tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T45_;
            nimZeroMem((void *)(&wX60gensym12__1),
                       sizeof(tyObject_Q__qTeNCUnOBz6tTOvSi0h19aQ));
            colontmpD__4.len = 0;
            colontmpD__4.p = NIM_NIL;
	    printf("calling n__w_u_u1138(h_1);\n");
            wX60gensym12__1 = n__w_u1138(h_1);
	    printf("called n__w_u_u1138(h_1);\n");
            if (NIM_UNLIKELY(*nimErr_))
              goto LA43_;
            T45_.len = 0;
            T45_.p = NIM_NIL;
            switch (wX60gensym12__1.g) {
            case NIM_FALSE: {
              tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA T47_;
              nimZeroMem((void *)(&T47_),
                         sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
              eqsink___w_u1286(Result, (&T47_));
              eqdestroy___w_u42(colontmpD__4);
              eqdestroy___w_u1160((&wX60gensym12__1));
              eqdestroy___w_u1113((&wX60gensym9__1));
	      printf("calling eqdestroy___t_u238((&h_1));\n");
              eqdestroy___t_u238((&h_1));
	      printf("called eqdestroy___t_u238((&h_1));\n");
              eqdestroy___t_u238((&w_1));
              goto BeforeRet_;
            } break;
            case NIM_TRUE: {
              if (!(((2 & ((NU8)1 << ((NU)((wX60gensym12__1.g)) & 7U))) !=
                     0))) {
                raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_13,
                                 (NI)(wX60gensym12__1.g));
                goto LA43_;
              }
              colontmpD__4 = wX60gensym12__1._g_2.z;
              if (!(((2 & ((NU8)1 << ((NU)((wX60gensym12__1.g)) & 7U))) !=
                     0))) {
                raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_14,
                                 (NI)(wX60gensym12__1.g));
                goto LA43_;
              }
              eqwasMoved___w_u39((&wX60gensym12__1._g_2.z));
              T45_ = colontmpD__4;
            } break;
            default: {
            } break;
            }
            T44_ = T45_.len;
            d_1 = T44_;
            {
              tyArray__vEOa9c5qaE9ajWxR5R4zwfQg T54_;
              if (!(d_1 == ((NI)32)))
                goto LA52_;
              nimZeroMem((void *)T54_,
                         sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
              w__w_u1230(T54_);
              if (NIM_UNLIKELY(*nimErr_))
                goto LA43_;
              (void)(T54_);
              (*Result).g = NIM_TRUE;
              nimZeroMem((void *)(&(*Result)._g_2.z),
                         sizeof(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw));
              (*Result)._g_2.z.kind = ((NI)1);
              nimZeroMem((void *)(*Result)._g_2.z._kind_2.e,
                         sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
              (*Result)._g_2.z._kind_2.r = 0;
              eqdestroy___w_u42(colontmpD__4);
              eqdestroy___w_u1160((&wX60gensym12__1));
              eqdestroy___w_u1113((&wX60gensym9__1));
	      printf("calling eqdestroy___t_u238((&h_1)) callsite 1\n");
              eqdestroy___t_u238((&h_1));
	      printf("called eqdestroy___t_u238((&h_1)) callsite 1;\n");
              eqdestroy___t_u238((&w_1));
              goto BeforeRet_;
            }
            goto LA50_;
          LA52_:;
            {
              if (!(d_1 == ((NI)0)))
                goto LA56_;
              (*Result).g = NIM_TRUE;
              nimZeroMem((void *)(&(*Result)._g_2.z),
                         sizeof(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw));
              (*Result)._g_2.z.kind = ((NI)2);
              eqdestroy___w_u42(colontmpD__4);
              eqdestroy___w_u1160((&wX60gensym12__1));
              eqdestroy___w_u1113((&wX60gensym9__1));
              eqdestroy___t_u238((&h_1));
              eqdestroy___t_u238((&w_1));
              goto BeforeRet_;
            }
            goto LA50_;
          LA56_:;
          LA50_:;
            nimZeroMem((void *)Result,
                       sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
            (*Result).g = NIM_FALSE;
            eqdestroy___w_u42(colontmpD__4);
            eqdestroy___w_u1160((&wX60gensym12__1));
            eqdestroy___w_u1113((&wX60gensym9__1));
            eqdestroy___t_u238((&h_1));
            eqdestroy___t_u238((&w_1));
            goto BeforeRet_;
            {
            LA43_:;
            }
            {
              eqdestroy___w_u42(colontmpD__4);
              eqdestroy___w_u1160((&wX60gensym12__1));
            }
            if (NIM_UNLIKELY(*nimErr_))
              goto LA17_;
          }
        LA23_:;
          {
          LA17_:;
          }
          {
            eqdestroy___w_u1113((&wX60gensym9__1));
            eqdestroy___t_u238((&h_1));
          }
          if (NIM_UNLIKELY(*nimErr_))
            goto LA1_;
        }
      LA4_:;
      }
    }
    {
    LA1_:;
    }
    {
      eqdestroy___t_u238((&w_1));
    }
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  printf("finished p__w_u1232\n");
}
N_LIB_PRIVATE N_NIMCALL(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ,
                        u__w_u1344)(NU8 *data_p0, NI data_p0Len_0) {
  tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ result;
  result.bytes = at___t_u165(data_p0, data_p0Len_0);
  result.position = ((NI)0);
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___w_u1312)(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw *dest_p0) {
  (*dest_p0).kind = 0;
  switch ((*dest_p0).kind) {
  case ((NI)2): {
  } break;
  case ((NI)1): {
    nimZeroMem((void *)(*dest_p0)._kind_2.e,
               sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
    (*dest_p0)._kind_2.r = 0;
  } break;
  case ((NI)0): {
    (*dest_p0).p.len = 0;
    (*dest_p0).p.p = NIM_NIL;
  } break;
  default:
    __builtin_unreachable();
  }
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1315)(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw *dest_p0) {
  printf("starting eqdestroy___w_1315: %p\n", (void *)dest_p0);
  switch ((*dest_p0).kind) {
  case ((NI)2): {
  } break;
  case ((NI)1): {
  } break;
  case ((NI)0): {
    eqdestroy___w_u42((*dest_p0).p);
  } break;
  default:
    __builtin_unreachable();
  }
  printf("finished eqdestroy___w_1315: %p\n", (void *)dest_p0);
}
N_LIB_PRIVATE N_NIMCALL(void,
                        v__w_u1350)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ g_p0) {
  printf("starting v_w_u1350\n");
  NU8 e_1;
  NIM_BOOL oldNimErrFin3_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    e_1 = ((NU8)64);
    {
      while (1) {
        tyObject_BcolonObjectType___qRQIF8n6ULu1H5MHwOhPIg *t_1;
        tySequence__6H5Oh5UUvVCLiakt9aTwtUQ node_1;
        tyObject_K__T0CnLg5itDR3hHLPCD9bvdw next_1;
        tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA colontmpD_;
        tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ colontmpD__2;
        tyArray__ekVvh9bp9cVe7STNUL8R406w T4_;
        tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA T5_;
        t_1 = NIM_NIL;
        node_1.len = 0;
        node_1.p = NIM_NIL;
        nimZeroMem((void *)(&next_1),
                   sizeof(tyObject_K__T0CnLg5itDR3hHLPCD9bvdw));
        nimZeroMem((void *)(&colontmpD_),
                   sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
        nimZeroMem((void *)(&colontmpD__2),
                   sizeof(tyObject_L__2Oe2Fb2uKyK7RF7uK8bFgQ));
        t_1 = new__w_u1353();
        x__w_u290(&t_1, T4_, 0);
        if (NIM_UNLIKELY(*nimErr_))
          goto LA3_;
        node_1 = g_p0;
        colontmpD__2 =
            u__w_u1344(((node_1).p) ? (node_1.p->data) : NIM_NIL, node_1.len);
        if (NIM_UNLIKELY(*nimErr_))
          goto LA3_;
        nimZeroMem((void *)(&T5_),
                   sizeof(tyObject_Q__eMmU8xC9bijyWK9b5Lj02u9bA));
        p__w_u1232(colontmpD__2, e_1, (&T5_));
        if (NIM_UNLIKELY(*nimErr_))
          goto LA3_;
        eqsink___w_u1286((&colontmpD_), (&T5_));
        if (!(((2 & ((NU8)1 << ((NU)((colontmpD_.g)) & 7U))) != 0))) {
          raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_15, (NI)(colontmpD_.g));
          goto LA3_;
        }
        next_1 = colontmpD_._g_2.z;
        if (!(((2 & ((NU8)1 << ((NU)((colontmpD_.g)) & 7U))) != 0))) {
          raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_16, (NI)(colontmpD_.g));
          goto LA3_;
        }
        eqwasMoved___w_u1312((&colontmpD_._g_2.z));
        switch (next_1.kind) {
        case ((NI)0):
        case ((NI)2): {
          eqdestroy___t_u238((&colontmpD__2));
          eqdestroy___w_u1277((&colontmpD_));
          eqdestroy___w_u1315((&next_1));
          eqdestroy___w_u920(t_1);
          if (NIM_UNLIKELY(*nimErr_))
            goto BeforeRet_;
          goto BeforeRet_;
        } break;
        case ((NI)1): {
          if (!(((2 & ((NU8)1 << ((NU)((next_1.kind)) & 7U))) != 0))) {
            raiseFieldError2(TM__uos5llwHv3fXsxhC8qvS9cw_18, (NI)(next_1.kind));
            goto LA3_;
          }
          e_1 = next_1._kind_2.r;
        } break;
        default:
          __builtin_unreachable();
        }
        {
        LA3_:;
        }
        {
          oldNimErrFin3_ = *nimErr_;
          *nimErr_ = NIM_FALSE;
          eqdestroy___t_u238((&colontmpD__2));
          eqdestroy___w_u1277((&colontmpD_));
          eqdestroy___w_u1315((&next_1));
          eqdestroy___w_u920(t_1);
          if (NIM_UNLIKELY(*nimErr_))
            goto BeforeRet_;
          *nimErr_ = oldNimErrFin3_;
        }
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    }
  }
BeforeRet_:;
  printf("finished v_w_u1350\n");
}
N_LIB_PRIVATE N_NIMCALL(tySequence__aLjCOs9bu5l2rz6ENM6m6Sg, y__w_u4)(void) {
  tySequence__aLjCOs9bu5l2rz6ENM6m6Sg result;
  result.len = 2;
  result.p = (tySequence__aLjCOs9bu5l2rz6ENM6m6Sg_Content *)newSeqPayload(
      2, sizeof(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ),
      NIM_ALIGNOF(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ));
  result.p->data[0].len = 179;
  result.p->data[0].p =
      (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content *)newSeqPayload(
          179, sizeof(NU8), NIM_ALIGNOF(NU8));
  result.p->data[0].p->data[0] = ((NU8)248);
  result.p->data[0].p->data[1] = ((NU8)177);
  result.p->data[0].p->data[2] = ((NU8)160);
  result.p->data[0].p->data[3] = ((NU8)129);
  result.p->data[0].p->data[4] = ((NU8)136);
  result.p->data[0].p->data[5] = ((NU8)149);
  result.p->data[0].p->data[6] = ((NU8)159);
  result.p->data[0].p->data[7] = ((NU8)31);
  result.p->data[0].p->data[8] = ((NU8)252);
  result.p->data[0].p->data[9] = ((NU8)215);
  result.p->data[0].p->data[10] = ((NU8)147);
  result.p->data[0].p->data[11] = ((NU8)250);
  result.p->data[0].p->data[12] = ((NU8)28);
  result.p->data[0].p->data[13] = ((NU8)74);
  result.p->data[0].p->data[14] = ((NU8)127);
  result.p->data[0].p->data[15] = ((NU8)243);
  result.p->data[0].p->data[16] = ((NU8)250);
  result.p->data[0].p->data[17] = ((NU8)52);
  result.p->data[0].p->data[18] = ((NU8)43);
  result.p->data[0].p->data[19] = ((NU8)117);
  result.p->data[0].p->data[20] = ((NU8)253);
  result.p->data[0].p->data[21] = ((NU8)206);
  result.p->data[0].p->data[22] = ((NU8)185);
  result.p->data[0].p->data[23] = ((NU8)136);
  result.p->data[0].p->data[24] = ((NU8)179);
  result.p->data[0].p->data[25] = ((NU8)23);
  result.p->data[0].p->data[26] = ((NU8)70);
  result.p->data[0].p->data[27] = ((NU8)75);
  result.p->data[0].p->data[28] = ((NU8)37);
  result.p->data[0].p->data[29] = ((NU8)169);
  result.p->data[0].p->data[30] = ((NU8)40);
  result.p->data[0].p->data[31] = ((NU8)81);
  result.p->data[0].p->data[32] = ((NU8)139);
  result.p->data[0].p->data[33] = ((NU8)29);
  result.p->data[0].p->data[34] = ((NU8)85);
  result.p->data[0].p->data[35] = ((NU8)128);
  result.p->data[0].p->data[36] = ((NU8)160);
  result.p->data[0].p->data[37] = ((NU8)166);
  result.p->data[0].p->data[38] = ((NU8)92);
  result.p->data[0].p->data[39] = ((NU8)64);
  result.p->data[0].p->data[40] = ((NU8)107);
  result.p->data[0].p->data[41] = ((NU8)103);
  result.p->data[0].p->data[42] = ((NU8)166);
  result.p->data[0].p->data[43] = ((NU8)196);
  result.p->data[0].p->data[44] = ((NU8)94);
  result.p->data[0].p->data[45] = ((NU8)147);
  result.p->data[0].p->data[46] = ((NU8)183);
  result.p->data[0].p->data[47] = ((NU8)129);
  result.p->data[0].p->data[48] = ((NU8)212);
  result.p->data[0].p->data[49] = ((NU8)225);
  result.p->data[0].p->data[50] = ((NU8)123);
  result.p->data[0].p->data[51] = ((NU8)145);
  result.p->data[0].p->data[52] = ((NU8)5);
  result.p->data[0].p->data[53] = ((NU8)105);
  result.p->data[0].p->data[54] = ((NU8)226);
  result.p->data[0].p->data[55] = ((NU8)248);
  result.p->data[0].p->data[56] = ((NU8)243);
  result.p->data[0].p->data[57] = ((NU8)193);
  result.p->data[0].p->data[58] = ((NU8)9);
  result.p->data[0].p->data[59] = ((NU8)179);
  result.p->data[0].p->data[60] = ((NU8)25);
  result.p->data[0].p->data[61] = ((NU8)169);
  result.p->data[0].p->data[62] = ((NU8)168);
  result.p->data[0].p->data[63] = ((NU8)252);
  result.p->data[0].p->data[64] = ((NU8)112);
  result.p->data[0].p->data[65] = ((NU8)223);
  result.p->data[0].p->data[66] = ((NU8)115);
  result.p->data[0].p->data[67] = ((NU8)37);
  result.p->data[0].p->data[68] = ((NU8)41);
  result.p->data[0].p->data[69] = ((NU8)128);
  result.p->data[0].p->data[70] = ((NU8)160);
  result.p->data[0].p->data[71] = ((NU8)212);
  result.p->data[0].p->data[72] = ((NU8)49);
  result.p->data[0].p->data[73] = ((NU8)8);
  result.p->data[0].p->data[74] = ((NU8)53);
  result.p->data[0].p->data[75] = ((NU8)235);
  result.p->data[0].p->data[76] = ((NU8)82);
  result.p->data[0].p->data[77] = ((NU8)204);
  result.p->data[0].p->data[78] = ((NU8)21);
  result.p->data[0].p->data[79] = ((NU8)4);
  result.p->data[0].p->data[80] = ((NU8)254);
  result.p->data[0].p->data[81] = ((NU8)38);
  result.p->data[0].p->data[82] = ((NU8)152);
  result.p->data[0].p->data[83] = ((NU8)121);
  result.p->data[0].p->data[84] = ((NU8)245);
  result.p->data[0].p->data[85] = ((NU8)19);
  result.p->data[0].p->data[86] = ((NU8)127);
  result.p->data[0].p->data[87] = ((NU8)137);
  result.p->data[0].p->data[88] = ((NU8)243);
  result.p->data[0].p->data[89] = ((NU8)84);
  result.p->data[0].p->data[90] = ((NU8)79);
  result.p->data[0].p->data[91] = ((NU8)146);
  result.p->data[0].p->data[92] = ((NU8)233);
  result.p->data[0].p->data[93] = ((NU8)16);
  result.p->data[0].p->data[94] = ((NU8)10);
  result.p->data[0].p->data[95] = ((NU8)222);
  result.p->data[0].p->data[96] = ((NU8)19);
  result.p->data[0].p->data[97] = ((NU8)147);
  result.p->data[0].p->data[98] = ((NU8)71);
  result.p->data[0].p->data[99] = ((NU8)196);
  result.p->data[0].p->data[100] = ((NU8)38);
  result.p->data[0].p->data[101] = ((NU8)5);
  result.p->data[0].p->data[102] = ((NU8)6);
  result.p->data[0].p->data[103] = ((NU8)128);
  result.p->data[0].p->data[104] = ((NU8)128);
  result.p->data[0].p->data[105] = ((NU8)128);
  result.p->data[0].p->data[106] = ((NU8)128);
  result.p->data[0].p->data[107] = ((NU8)128);
  result.p->data[0].p->data[108] = ((NU8)160);
  result.p->data[0].p->data[109] = ((NU8)194);
  result.p->data[0].p->data[110] = ((NU8)171);
  result.p->data[0].p->data[111] = ((NU8)71);
  result.p->data[0].p->data[112] = ((NU8)247);
  result.p->data[0].p->data[113] = ((NU8)21);
  result.p->data[0].p->data[114] = ((NU8)130);
  result.p->data[0].p->data[115] = ((NU8)2);
  result.p->data[0].p->data[116] = ((NU8)59);
  result.p->data[0].p->data[117] = ((NU8)51);
  result.p->data[0].p->data[118] = ((NU8)27);
  result.p->data[0].p->data[119] = ((NU8)110);
  result.p->data[0].p->data[120] = ((NU8)162);
  result.p->data[0].p->data[121] = ((NU8)104);
  result.p->data[0].p->data[122] = ((NU8)73);
  result.p->data[0].p->data[123] = ((NU8)163);
  result.p->data[0].p->data[124] = ((NU8)174);
  result.p->data[0].p->data[125] = ((NU8)229);
  result.p->data[0].p->data[126] = ((NU8)43);
  result.p->data[0].p->data[127] = ((NU8)72);
  result.p->data[0].p->data[128] = ((NU8)28);
  result.p->data[0].p->data[129] = ((NU8)43);
  result.p->data[0].p->data[130] = ((NU8)246);
  result.p->data[0].p->data[131] = ((NU8)103);
  result.p->data[0].p->data[132] = ((NU8)5);
  result.p->data[0].p->data[133] = ((NU8)27);
  result.p->data[0].p->data[134] = ((NU8)137);
  result.p->data[0].p->data[135] = ((NU8)130);
  result.p->data[0].p->data[136] = ((NU8)21);
  result.p->data[0].p->data[137] = ((NU8)106);
  result.p->data[0].p->data[138] = ((NU8)1);
  result.p->data[0].p->data[139] = ((NU8)201);
  result.p->data[0].p->data[140] = ((NU8)49);
  result.p->data[0].p->data[141] = ((NU8)128);
  result.p->data[0].p->data[142] = ((NU8)128);
  result.p->data[0].p->data[143] = ((NU8)128);
  result.p->data[0].p->data[144] = ((NU8)128);
  result.p->data[0].p->data[145] = ((NU8)160);
  result.p->data[0].p->data[146] = ((NU8)198);
  result.p->data[0].p->data[147] = ((NU8)39);
  result.p->data[0].p->data[148] = ((NU8)225);
  result.p->data[0].p->data[149] = ((NU8)154);
  result.p->data[0].p->data[150] = ((NU8)149);
  result.p->data[0].p->data[151] = ((NU8)227);
  result.p->data[0].p->data[152] = ((NU8)112);
  result.p->data[0].p->data[153] = ((NU8)175);
  result.p->data[0].p->data[154] = ((NU8)149);
  result.p->data[0].p->data[155] = ((NU8)233);
  result.p->data[0].p->data[156] = ((NU8)24);
  result.p->data[0].p->data[157] = ((NU8)177);
  result.p->data[0].p->data[158] = ((NU8)216);
  result.p->data[0].p->data[159] = ((NU8)49);
  result.p->data[0].p->data[160] = ((NU8)194);
  result.p->data[0].p->data[161] = ((NU8)32);
  result.p->data[0].p->data[162] = ((NU8)227);
  result.p->data[0].p->data[163] = ((NU8)116);
  result.p->data[0].p->data[164] = ((NU8)223);
  result.p->data[0].p->data[165] = ((NU8)82);
  result.p->data[0].p->data[166] = ((NU8)202);
  result.p->data[0].p->data[167] = ((NU8)202);
  result.p->data[0].p->data[168] = ((NU8)87);
  result.p->data[0].p->data[169] = ((NU8)37);
  result.p->data[0].p->data[170] = ((NU8)129);
  result.p->data[0].p->data[171] = ((NU8)92);
  result.p->data[0].p->data[172] = ((NU8)198);
  result.p->data[0].p->data[173] = ((NU8)14);
  result.p->data[0].p->data[174] = ((NU8)198);
  result.p->data[0].p->data[175] = ((NU8)134);
  result.p->data[0].p->data[176] = ((NU8)161);
  result.p->data[0].p->data[177] = ((NU8)216);
  result.p->data[0].p->data[178] = ((NU8)128);
  result.p->data[1].len = 30;
  result.p->data[1].p =
      (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content *)newSeqPayload(
          30, sizeof(NU8), NIM_ALIGNOF(NU8));
  result.p->data[1].p->data[0] = ((NU8)0);
  result.p->data[1].p->data[1] = ((NU8)0);
  result.p->data[1].p->data[2] = ((NU8)0);
  result.p->data[1].p->data[3] = ((NU8)0);
  result.p->data[1].p->data[4] = ((NU8)0);
  result.p->data[1].p->data[5] = ((NU8)0);
  result.p->data[1].p->data[6] = ((NU8)0);
  result.p->data[1].p->data[7] = ((NU8)0);
  result.p->data[1].p->data[8] = ((NU8)0);
  result.p->data[1].p->data[9] = ((NU8)0);
  result.p->data[1].p->data[10] = ((NU8)0);
  result.p->data[1].p->data[11] = ((NU8)0);
  result.p->data[1].p->data[12] = ((NU8)0);
  result.p->data[1].p->data[13] = ((NU8)0);
  result.p->data[1].p->data[14] = ((NU8)0);
  result.p->data[1].p->data[15] = ((NU8)0);
  result.p->data[1].p->data[16] = ((NU8)0);
  result.p->data[1].p->data[17] = ((NU8)0);
  result.p->data[1].p->data[18] = ((NU8)0);
  result.p->data[1].p->data[19] = ((NU8)0);
  result.p->data[1].p->data[20] = ((NU8)0);
  result.p->data[1].p->data[21] = ((NU8)0);
  result.p->data[1].p->data[22] = ((NU8)0);
  result.p->data[1].p->data[23] = ((NU8)0);
  result.p->data[1].p->data[24] = ((NU8)0);
  result.p->data[1].p->data[25] = ((NU8)0);
  result.p->data[1].p->data[26] = ((NU8)0);
  result.p->data[1].p->data[27] = ((NU8)0);
  result.p->data[1].p->data[28] = ((NU8)0);
  result.p->data[1].p->data[29] = ((NU8)0);
  return result;
}

N_LIB_PRIVATE void PreMainInner(void) { atmedotnim_Init000(); }

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char **cmdLine;
N_LIB_PRIVATE char **gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
  atpsystemdotnim_Init000();
  PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) { NimMainModule(); }

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
  PreMain();
  NimMainInner();
#endif
}

int main(int argc, char **args, char **env) {
  cmdLine = args;
  cmdCount = argc;
  gEnv = env;
  NimMain();
  return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
  {
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng colontmpD_;
    tySequence__aLjCOs9bu5l2rz6ENM6m6Sg colontmpD__2;
    NIM_BOOL *nimErr_;
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&colontmpD_),
               sizeof(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng));
    colontmpD__2.len = 0;
    colontmpD__2.p = NIM_NIL;
    colontmpD_ = toTable__w_u1365(TM__uos5llwHv3fXsxhC8qvS9cw_2, 1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    (void)(colontmpD_);
    colontmpD__2 = y__w_u4();
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (((NI)0) < 0 || ((NI)0) >= colontmpD__2.len) {
      raiseIndexError2(((NI)0), colontmpD__2.len - 1);
      goto BeforeRet_;
    }
    v__w_u1350(colontmpD__2.p->data[((NI)0)]);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    eqdestroy___w_u21(colontmpD__2);
    eqdestroy___w_u1529((&colontmpD_));
    eqdestroy___e_u775((&h__e_u11));
    eqdestroy___e_u650(s__e_u5);
  BeforeRet_:;
    nimTestErrorFlag();
  }
}
