/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw
    tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw;
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw {
  NU64 Field0;
  NU64 Field1;
};
static N_INLINE(NU64, hashFarm__pureZhashes_u525)(NU8 *s_p0, NI s_p0Len_0);
static N_INLINE(NU64, len016__pureZhashes_u379)(NU8 *s_p0, NI s_p0Len_0);
static N_INLINE(NU64, lenU__pureZhashes_u339)(NU8 *s_p0, NI s_p0Len_0);
static N_INLINE(NU64, load8__pureZhashes_u335)(NU8 *s_p0, NI s_p0Len_0,
                                               NI o_p1);
static N_INLINE(void, copyMem__system_u1741)(void *dest_p0, void *source_p1,
                                             NI size_p2);
static N_INLINE(void, nimCopyMem)(void *dest_p0, void *source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NU64, rotR__pureZhashes_u352)(NU64 v_p0, int bits_p1);
static N_INLINE(NU64, len16__pureZhashes_u364)(NU64 u_p0, NU64 v_p1,
                                               NU64 mul_p2);
static N_INLINE(NU32, load4__pureZhashes_u331)(NU8 *s_p0, NI s_p0Len_0,
                                               NI o_p1);
static N_INLINE(NU64, shiftMix__pureZhashes_u345)(NU64 v_p0);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
static N_INLINE(NU64, len1732__pureZhashes_u431)(NU8 *s_p0, NI s_p0Len_0);
static N_INLINE(NU64, len3364__pureZhashes_u445)(NU8 *s_p0, NI s_p0Len_0);
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2);
static N_INLINE(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw,
                weakLen32withSeeds__pureZhashes_u499)(NU8 *s_p0, NI s_p0Len_0,
                                                      NI o_p1, NU64 a_p2,
                                                      NU64 b_p3);
static N_INLINE(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw,
                weakLen32withSeeds2__pureZhashes_u476)(NU64 w_p0, NU64 x_p1,
                                                       NU64 y_p2, NU64 z_p3,
                                                       NU64 a_p4, NU64 b_p5);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static N_INLINE(NU64, lenU__pureZhashes_u339)(NU8 *s_p0, NI s_p0Len_0) {
  NU64 result;
  result = ((NU64)(s_p0Len_0));
  return result;
}
static N_INLINE(void, nimCopyMem)(void *dest_p0, void *source_p1, NI size_p2) {
  void *T1_;
  T1_ = (void *)0;
  T1_ = memcpy(dest_p0, source_p1, ((size_t)(size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void *dest_p0, void *source_p1,
                                             NI size_p2) {
  nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NU64, load8__pureZhashes_u335)(NU8 *s_p0, NI s_p0Len_0,
                                               NI o_p1) {
  NU64 result;
  {
    result = (NU64)0;
    result = 0ULL;
    if (o_p1 < 0 || o_p1 >= s_p0Len_0) {
      raiseIndexError2(o_p1, s_p0Len_0 - 1);
      goto BeforeRet_;
    }
    copyMem__system_u1741(((void *)((&result))), ((void *)((&s_p0[o_p1]))),
                          ((NI)8));
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NU64, rotR__pureZhashes_u352)(NU64 v_p0, int bits_p1) {
  NU64 result;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_3;
  {
    if (nimSubInt(((NI32)64), bits_p1, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_3)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (TM__7tkD9cFJSchVDwHuwaY9bP9bA_3 < (-2147483647 - 1) ||
        TM__7tkD9cFJSchVDwHuwaY9bP9bA_3 > 2147483647) {
      raiseOverflow();
      goto BeforeRet_;
    }
    result = (NU64)((NU64)((NU64)(v_p0) >> (NU64)(bits_p1)) |
                    (NU64)((NU64)(v_p0)
                           << (NU64)((NI32)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_3))));
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NU64, len16__pureZhashes_u364)(NU64 u_p0, NU64 v_p1,
                                               NU64 mul_p2) {
  NU64 result;
  NU64 a_1;
  NU64 b_1;
  a_1 = (NU64)((NU64)((NU64)(u_p0 ^ v_p1)) * (NU64)(mul_p2));
  a_1 = (NU64)(a_1 ^ (NU64)((NU64)(a_1) >> (NU64)(((NI)47))));
  b_1 = (NU64)((NU64)((NU64)(v_p1 ^ a_1)) * (NU64)(mul_p2));
  b_1 = (NU64)(b_1 ^ (NU64)((NU64)(b_1) >> (NU64)(((NI)47))));
  result = (NU64)((NU64)(b_1) * (NU64)(mul_p2));
  return result;
}
static N_INLINE(NU32, load4__pureZhashes_u331)(NU8 *s_p0, NI s_p0Len_0,
                                               NI o_p1) {
  NU32 result;
  {
    result = (NU32)0;
    result = ((NU32)0);
    if (o_p1 < 0 || o_p1 >= s_p0Len_0) {
      raiseIndexError2(o_p1, s_p0Len_0 - 1);
      goto BeforeRet_;
    }
    copyMem__system_u1741(((void *)((&result))), ((void *)((&s_p0[o_p1]))),
                          ((NI)4));
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NU64, shiftMix__pureZhashes_u345)(NU64 v_p0) {
  NU64 result;
  result = (NU64)(v_p0 ^ (NU64)((NU64)(v_p0) >> (NU64)(((NI)47))));
  return result;
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
static N_INLINE(NU64, len016__pureZhashes_u379)(NU8 *s_p0, NI s_p0Len_0) {
  NU64 result;
  NU64 colontmpD_;
  NU64 colontmpD__2;
  NU64 colontmpD__3;
  NU64 colontmpD__4;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NU64)0;
    colontmpD_ = (NU64)0;
    colontmpD__2 = (NU64)0;
    colontmpD__3 = (NU64)0;
    colontmpD__4 = (NU64)0;
    {
      NU64 mul_1;
      NU64 T5_;
      NU64 a_1;
      NU64 T6_;
      NU64 b_1;
      NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_2;
      NU64 c_1;
      NU64 T7_;
      NU64 d_1;
      NU64 T8_;
      if (!(((NI)8) <= s_p0Len_0))
        goto LA3_;
      T5_ = (NU64)0;
      T5_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      mul_1 = (NU64)((NU64)(11160318154034397263ULL) +
                     (NU64)((NU64)((NU64)(2ULL) * (NU64)(T5_))));
      T6_ = (NU64)0;
      T6_ = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)0));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      a_1 = (NU64)((NU64)(T6_) + (NU64)(11160318154034397263ULL));
      if (nimSubInt(s_p0Len_0, ((NI)8), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_2)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      b_1 = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                    (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_2));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      T7_ = (NU64)0;
      T7_ = rotR__pureZhashes_u352(b_1, ((int)37));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      c_1 = (NU64)((NU64)((NU64)((NU64)(T7_) * (NU64)(mul_1))) + (NU64)(a_1));
      T8_ = (NU64)0;
      T8_ = rotR__pureZhashes_u352(a_1, ((int)25));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      d_1 = (NU64)((NU64)((NU64)((NU64)(T8_) + (NU64)(b_1))) * (NU64)(mul_1));
      colontmpD_ = len16__pureZhashes_u364(c_1, d_1, mul_1);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      result = colontmpD_;
    }
    goto LA1_;
  LA3_:;
    {
      NU64 mul_2;
      NU64 T12_;
      NU64 a_2;
      NU32 T13_;
      NU64 T14_;
      NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_4;
      NU32 T15_;
      if (!(((NI)4) <= s_p0Len_0))
        goto LA10_;
      T12_ = (NU64)0;
      T12_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      mul_2 = (NU64)((NU64)(11160318154034397263ULL) +
                     (NU64)((NU64)((NU64)(2ULL) * (NU64)(T12_))));
      T13_ = (NU32)0;
      T13_ = load4__pureZhashes_u331(s_p0, s_p0Len_0, ((NI)0));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      a_2 = ((NU64)(T13_));
      T14_ = (NU64)0;
      T14_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      if (nimSubInt(s_p0Len_0, ((NI)4), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_4)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      T15_ = (NU32)0;
      T15_ = load4__pureZhashes_u331(s_p0, s_p0Len_0,
                                     (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_4));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      colontmpD__2 = len16__pureZhashes_u364(
          (NU64)((NU64)(T14_) + (NU64)((NU64)((NU64)(a_2) << (NU64)(((NI)3))))),
          ((NU64)(T15_)), mul_2);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      result = colontmpD__2;
    }
    goto LA1_;
  LA10_:;
    {
      NU32 a_3;
      NU32 b_2;
      NU32 c_2;
      NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_5;
      NU32 y_1;
      NU64 z_1;
      NU64 T19_;
      NU64 T20_;
      if (!(((NI)0) < s_p0Len_0))
        goto LA17_;
      if (((NI)0) < 0 || ((NI)0) >= s_p0Len_0) {
        raiseIndexError2(((NI)0), s_p0Len_0 - 1);
        goto BeforeRet_;
      }
      a_3 = ((NU32)(s_p0[((NI)0)]));
      if ((NI)((NI64)(s_p0Len_0) >> (NU64)(((NI)1))) < 0 ||
          (NI)((NI64)(s_p0Len_0) >> (NU64)(((NI)1))) >= s_p0Len_0) {
        raiseIndexError2((NI)((NI64)(s_p0Len_0) >> (NU64)(((NI)1))),
                         s_p0Len_0 - 1);
        goto BeforeRet_;
      }
      b_2 = ((NU32)(s_p0[(NI)((NI64)(s_p0Len_0) >> (NU64)(((NI)1)))]));
      if (nimSubInt(s_p0Len_0, ((NI)1), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_5)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      if ((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_5) < 0 ||
          (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_5) >= s_p0Len_0) {
        raiseIndexError2((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_5), s_p0Len_0 - 1);
        goto BeforeRet_;
      }
      c_2 = ((NU32)(s_p0[(NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_5)]));
      y_1 =
          (NU32)((NU32)(a_3) + (NU32)((NU32)((NU64)(b_2) << (NU64)(((NI)8)))));
      T19_ = (NU64)0;
      T19_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      z_1 = (NU64)((NU64)(T19_) +
                   (NU64)(((NU64)((NU32)((NU64)(c_2) << (NU64)(((NI)2)))))));
      T20_ = (NU64)0;
      T20_ = shiftMix__pureZhashes_u345(
          (NU64)((NU64)((NU64)(((NU64)(y_1))) *
                        (NU64)(11160318154034397263ULL)) ^
                 (NU64)((NU64)(z_1) * (NU64)(14097894508562428199ULL))));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      colontmpD__3 = (NU64)((NU64)(T20_) * (NU64)(11160318154034397263ULL));
      result = colontmpD__3;
    }
    goto LA1_;
  LA17_:;
    {
      colontmpD__4 = 11160318154034397263ULL;
      result = colontmpD__4;
    }
  LA1_:;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NU64, len1732__pureZhashes_u431)(NU8 *s_p0, NI s_p0Len_0) {
  NU64 result;
  NU64 mul_1;
  NU64 T1_;
  NU64 a_1;
  NU64 T2_;
  NU64 b_1;
  NU64 c_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_6;
  NU64 T3_;
  NU64 d_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_7;
  NU64 T4_;
  NU64 T5_;
  NU64 T6_;
  NU64 T7_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NU64)0;
    T1_ = (NU64)0;
    T1_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    mul_1 = (NU64)((NU64)(11160318154034397263ULL) +
                   (NU64)((NU64)((NU64)(2ULL) * (NU64)(T1_))));
    T2_ = (NU64)0;
    T2_ = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)0));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    a_1 = (NU64)((NU64)(T2_) * (NU64)(13011662864482103923ULL));
    b_1 = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)8));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimSubInt(s_p0Len_0, ((NI)8), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_6)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T3_ = (NU64)0;
    T3_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_6));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    c_1 = (NU64)((NU64)(T3_) * (NU64)(mul_1));
    if (nimSubInt(s_p0Len_0, ((NI)16), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_7)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T4_ = (NU64)0;
    T4_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_7));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    d_1 = (NU64)((NU64)(T4_) * (NU64)(11160318154034397263ULL));
    T5_ = (NU64)0;
    T5_ = rotR__pureZhashes_u352((NU64)((NU64)(a_1) + (NU64)(b_1)), ((int)43));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T6_ = (NU64)0;
    T6_ = rotR__pureZhashes_u352(c_1, ((int)30));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T7_ = (NU64)0;
    T7_ = rotR__pureZhashes_u352(
        (NU64)((NU64)(b_1) + (NU64)(11160318154034397263ULL)), ((int)18));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result = len16__pureZhashes_u364(
        (NU64)((NU64)((NU64)((NU64)(T5_) + (NU64)(T6_))) + (NU64)(d_1)),
        (NU64)((NU64)((NU64)((NU64)(a_1) + (NU64)(T7_))) + (NU64)(c_1)), mul_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NU64, len3364__pureZhashes_u445)(NU8 *s_p0, NI s_p0Len_0) {
  NU64 result;
  NU64 mul_1;
  NU64 T1_;
  NU64 a_1;
  NU64 T2_;
  NU64 b_1;
  NU64 c_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_8;
  NU64 T3_;
  NU64 d_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_9;
  NU64 T4_;
  NU64 y_1;
  NU64 T5_;
  NU64 T6_;
  NU64 z_1;
  NU64 T7_;
  NU64 e_1;
  NU64 T8_;
  NU64 f_1;
  NU64 g_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_10;
  NU64 T9_;
  NU64 h_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_11;
  NU64 T10_;
  NU64 T11_;
  NU64 T12_;
  NU64 T13_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NU64)0;
    T1_ = (NU64)0;
    T1_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    mul_1 = (NU64)((NU64)(11160318154034397263ULL) +
                   (NU64)((NU64)((NU64)(2ULL) * (NU64)(T1_))));
    T2_ = (NU64)0;
    T2_ = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)0));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    a_1 = (NU64)((NU64)(T2_) * (NU64)(11160318154034397263ULL));
    b_1 = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)8));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimSubInt(s_p0Len_0, ((NI)8), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_8)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T3_ = (NU64)0;
    T3_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    c_1 = (NU64)((NU64)(T3_) * (NU64)(mul_1));
    if (nimSubInt(s_p0Len_0, ((NI)16), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_9)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T4_ = (NU64)0;
    T4_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_9));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    d_1 = (NU64)((NU64)(T4_) * (NU64)(11160318154034397263ULL));
    T5_ = (NU64)0;
    T5_ = rotR__pureZhashes_u352((NU64)((NU64)(a_1) + (NU64)(b_1)), ((int)43));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T6_ = (NU64)0;
    T6_ = rotR__pureZhashes_u352(c_1, ((int)30));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    y_1 = (NU64)((NU64)((NU64)((NU64)(T5_) + (NU64)(T6_))) + (NU64)(d_1));
    T7_ = (NU64)0;
    T7_ = rotR__pureZhashes_u352(
        (NU64)((NU64)(b_1) + (NU64)(11160318154034397263ULL)), ((int)18));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    z_1 = len16__pureZhashes_u364(
        y_1, (NU64)((NU64)((NU64)((NU64)(a_1) + (NU64)(T7_))) + (NU64)(c_1)),
        mul_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T8_ = (NU64)0;
    T8_ = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)16));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    e_1 = (NU64)((NU64)(T8_) * (NU64)(mul_1));
    f_1 = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)24));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimSubInt(s_p0Len_0, ((NI)32), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_10)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T9_ = (NU64)0;
    T9_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_10));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    g_1 = (NU64)((NU64)((NU64)((NU64)(y_1) + (NU64)(T9_))) * (NU64)(mul_1));
    if (nimSubInt(s_p0Len_0, ((NI)24), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_11)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T10_ = (NU64)0;
    T10_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                   (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_11));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    h_1 = (NU64)((NU64)((NU64)((NU64)(z_1) + (NU64)(T10_))) * (NU64)(mul_1));
    T11_ = (NU64)0;
    T11_ = rotR__pureZhashes_u352((NU64)((NU64)(e_1) + (NU64)(f_1)), ((int)43));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T12_ = (NU64)0;
    T12_ = rotR__pureZhashes_u352(g_1, ((int)30));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T13_ = (NU64)0;
    T13_ = rotR__pureZhashes_u352((NU64)((NU64)(f_1) + (NU64)(a_1)), ((int)18));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result = len16__pureZhashes_u364(
        (NU64)((NU64)((NU64)((NU64)(T11_) + (NU64)(T12_))) + (NU64)(h_1)),
        (NU64)((NU64)((NU64)((NU64)(e_1) + (NU64)(T13_))) + (NU64)(g_1)),
        mul_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2) {
  void *T1_;
  T1_ = (void *)0;
  T1_ = memset(a_p0, v_p1, ((size_t)(size_p2)));
}
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw,
                weakLen32withSeeds2__pureZhashes_u476)(NU64 w_p0, NU64 x_p1,
                                                       NU64 y_p2, NU64 z_p3,
                                                       NU64 a_p4, NU64 b_p5) {
  tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw result;
  NU64 a_2;
  NU64 b_2;
  NU64 c_1;
  NU64 T1_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result), sizeof(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw));
    a_2 = (NU64)((NU64)(a_p4) + (NU64)(w_p0));
    b_2 = rotR__pureZhashes_u352(
        (NU64)((NU64)((NU64)((NU64)(b_p5) + (NU64)(a_2))) + (NU64)(z_p3)),
        ((int)21));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    c_1 = a_2;
    a_2 += x_p1;
    a_2 += y_p2;
    T1_ = (NU64)0;
    T1_ = rotR__pureZhashes_u352(a_2, ((int)44));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    b_2 += T1_;
    result.Field0 = (NU64)((NU64)(a_2) + (NU64)(z_p3));
    result.Field1 = (NU64)((NU64)(b_2) + (NU64)(c_1));
  }
BeforeRet_:;
  return result;
}
static N_INLINE(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw,
                weakLen32withSeeds__pureZhashes_u499)(NU8 *s_p0, NI s_p0Len_0,
                                                      NI o_p1, NU64 a_p2,
                                                      NU64 b_p3) {
  tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw result;
  NU64 T1_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_20;
  NU64 T2_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_21;
  NU64 T3_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_22;
  NU64 T4_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result), sizeof(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw));
    T1_ = (NU64)0;
    T1_ = load8__pureZhashes_u335(s_p0, s_p0Len_0, o_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimAddInt(o_p1, ((NI)8), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_20)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T2_ = (NU64)0;
    T2_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_20));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimAddInt(o_p1, ((NI)16), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_21)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T3_ = (NU64)0;
    T3_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_21));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimAddInt(o_p1, ((NI)24), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_22)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T4_ = (NU64)0;
    T4_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                  (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_22));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result =
        weakLen32withSeeds2__pureZhashes_u476(T1_, T2_, T3_, T4_, a_p2, b_p3);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NU64, hashFarm__pureZhashes_u525)(NU8 *s_p0, NI s_p0Len_0) {
  NU64 result;
  NI o_1;
  NU64 x_1;
  NU64 y_1;
  NU64 z_1;
  NU64 T13_;
  tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw v_1;
  tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw w_1;
  NU64 T14_;
  NI eos_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_12;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_13;
  NI last64_1;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_14;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_15;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_16;
  NU64 mul_1;
  NU64 T29_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_27;
  NU64 T30_;
  NU64 T31_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_28;
  NU64 T32_;
  NU64 T33_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_29;
  NU64 T34_;
  NU64 T35_;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_30;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_31;
  NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_32;
  NU64 T36_;
  NU64 T37_;
  NU64 T38_;
  NU64 T39_;
  NU64 T40_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NU64)0;
    {
      if (!(s_p0Len_0 <= ((NI)16)))
        goto LA3_;
      result = len016__pureZhashes_u379(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      goto BeforeRet_;
    }
  LA3_:;
    {
      if (!(s_p0Len_0 <= ((NI)32)))
        goto LA7_;
      result = len1732__pureZhashes_u431(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      goto BeforeRet_;
    }
  LA7_:;
    {
      if (!(s_p0Len_0 <= ((NI)64)))
        goto LA11_;
      result = len3364__pureZhashes_u445(s_p0, s_p0Len_0);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      goto BeforeRet_;
    }
  LA11_:;
    o_1 = ((NI)0);
    x_1 = 81ULL;
    y_1 = 2480279821605975764ULL;
    T13_ = (NU64)0;
    T13_ = shiftMix__pureZhashes_u345(
        (NU64)((NU64)((NU64)((NU64)(y_1) * (NU64)(11160318154034397263ULL))) +
               (NU64)(113ULL)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    z_1 = (NU64)((NU64)(T13_) * (NU64)(11160318154034397263ULL));
    nimZeroMem((void *)(&v_1), sizeof(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw));
    nimZeroMem((void *)(&w_1), sizeof(tyTuple__GviMuKbe9c3Hsi9c4x4m9avrw));
    T14_ = (NU64)0;
    T14_ = load8__pureZhashes_u335(s_p0, s_p0Len_0, ((NI)0));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    x_1 = (NU64)((NU64)((NU64)((NU64)(x_1) * (NU64)(11160318154034397263ULL))) +
                 (NU64)(T14_));
    if (nimSubInt(s_p0Len_0, ((NI)1), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_12)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimMulInt((NI)(((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_12)) / (((NI)64))),
                  ((NI)64), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_13)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    eos_1 = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_13);
    if (nimSubInt(s_p0Len_0, ((NI)1), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_14)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimAddInt(eos_1,
                  (NI)((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_14) & ((NI)63)),
                  &TM__7tkD9cFJSchVDwHuwaY9bP9bA_15)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimSubInt((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_15), ((NI)63),
                  &TM__7tkD9cFJSchVDwHuwaY9bP9bA_16)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    last64_1 = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_16);
    {
      while (1) {
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_17;
        NU64 T17_;
        NU64 T18_;
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_18;
        NU64 T19_;
        NU64 T20_;
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_19;
        NU64 T21_;
        NU64 T22_;
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_23;
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_24;
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_25;
        NU64 T23_;
        NU64 T24_;
        NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_26;
        if (nimAddInt(o_1, ((NI)8), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_17)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        T17_ = (NU64)0;
        T17_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                       (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_17));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        T18_ = (NU64)0;
        T18_ = rotR__pureZhashes_u352(
            (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(x_1) + (NU64)(y_1))) +
                                 (NU64)(v_1.Field0))) +
                   (NU64)(T17_)),
            ((int)37));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        x_1 = (NU64)((NU64)(T18_) * (NU64)(13011662864482103923ULL));
        if (nimAddInt(o_1, ((NI)48), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_18)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        T19_ = (NU64)0;
        T19_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                       (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_18));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        T20_ = (NU64)0;
        T20_ = rotR__pureZhashes_u352(
            (NU64)((NU64)((NU64)((NU64)(y_1) + (NU64)(v_1.Field1))) +
                   (NU64)(T19_)),
            ((int)42));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        y_1 = (NU64)((NU64)(T20_) * (NU64)(13011662864482103923ULL));
        x_1 = (NU64)(x_1 ^ w_1.Field1);
        if (nimAddInt(o_1, ((NI)40), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_19)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        T21_ = (NU64)0;
        T21_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                       (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_19));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        y_1 += (NU64)((NU64)(v_1.Field0) + (NU64)(T21_));
        T22_ = (NU64)0;
        T22_ = rotR__pureZhashes_u352((NU64)((NU64)(z_1) + (NU64)(w_1.Field0)),
                                      ((int)33));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        z_1 = (NU64)((NU64)(T22_) * (NU64)(13011662864482103923ULL));
        if (nimAddInt(o_1, ((NI)0), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_23)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        v_1 = weakLen32withSeeds__pureZhashes_u499(
            s_p0, s_p0Len_0, (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_23),
            (NU64)((NU64)(v_1.Field1) * (NU64)(13011662864482103923ULL)),
            (NU64)((NU64)(x_1) + (NU64)(w_1.Field0)));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (nimAddInt(o_1, ((NI)32), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_24)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        if (nimAddInt(o_1, ((NI)16), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_25)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        T23_ = (NU64)0;
        T23_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                       (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_25));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        w_1 = weakLen32withSeeds__pureZhashes_u499(
            s_p0, s_p0Len_0, (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_24),
            (NU64)((NU64)(z_1) + (NU64)(w_1.Field1)),
            (NU64)((NU64)(y_1) + (NU64)(T23_)));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        T24_ = (NU64)0;
        T24_ = z_1;
        z_1 = x_1;
        x_1 = T24_;
        if (nimAddInt(o_1, ((NI)64), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_26)) {
          raiseOverflow();
          goto BeforeRet_;
        };
        o_1 = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_26);
        {
          if (!(o_1 == eos_1))
            goto LA27_;
          goto LA15;
        }
      LA27_:;
      }
    }
  LA15:;
    mul_1 =
        (NU64)((NU64)(13011662864482103923ULL) +
               (NU64)((NU64)((NU64)((NU64)(z_1 & 255ULL)) << (NU64)(((NI)1)))));
    o_1 = last64_1;
    T29_ = (NU64)0;
    T29_ = lenU__pureZhashes_u339(s_p0, s_p0Len_0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    w_1.Field0 += (NU64)((NU64)((NU64)(T29_) - (NU64)(1ULL)) & 63ULL);
    v_1.Field0 += w_1.Field0;
    w_1.Field0 += v_1.Field0;
    if (nimAddInt(o_1, ((NI)8), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_27)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T30_ = (NU64)0;
    T30_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                   (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_27));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T31_ = (NU64)0;
    T31_ = rotR__pureZhashes_u352(
        (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(x_1) + (NU64)(y_1))) +
                             (NU64)(v_1.Field0))) +
               (NU64)(T30_)),
        ((int)37));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    x_1 = (NU64)((NU64)(T31_) * (NU64)(mul_1));
    if (nimAddInt(o_1, ((NI)48), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_28)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T32_ = (NU64)0;
    T32_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                   (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_28));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T33_ = (NU64)0;
    T33_ = rotR__pureZhashes_u352(
        (NU64)((NU64)((NU64)((NU64)(y_1) + (NU64)(v_1.Field1))) + (NU64)(T32_)),
        ((int)42));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    y_1 = (NU64)((NU64)(T33_) * (NU64)(mul_1));
    x_1 = (NU64)(x_1 ^ (NU64)((NU64)(w_1.Field1) * (NU64)(9ULL)));
    if (nimAddInt(o_1, ((NI)40), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_29)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T34_ = (NU64)0;
    T34_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                   (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_29));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    y_1 += (NU64)((NU64)((NU64)((NU64)(v_1.Field0) * (NU64)(9ULL))) +
                  (NU64)(T34_));
    T35_ = (NU64)0;
    T35_ = rotR__pureZhashes_u352((NU64)((NU64)(z_1) + (NU64)(w_1.Field0)),
                                  ((int)33));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    z_1 = (NU64)((NU64)(T35_) * (NU64)(mul_1));
    if (nimAddInt(o_1, ((NI)0), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_30)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    v_1 = weakLen32withSeeds__pureZhashes_u499(
        s_p0, s_p0Len_0, (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_30),
        (NU64)((NU64)(v_1.Field1) * (NU64)(mul_1)),
        (NU64)((NU64)(x_1) + (NU64)(w_1.Field0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    if (nimAddInt(o_1, ((NI)32), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_31)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimAddInt(o_1, ((NI)16), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_32)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T36_ = (NU64)0;
    T36_ = load8__pureZhashes_u335(s_p0, s_p0Len_0,
                                   (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_32));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    w_1 = weakLen32withSeeds__pureZhashes_u499(
        s_p0, s_p0Len_0, (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_31),
        (NU64)((NU64)(z_1) + (NU64)(w_1.Field1)),
        (NU64)((NU64)(y_1) + (NU64)(T36_)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T37_ = (NU64)0;
    T37_ = z_1;
    z_1 = x_1;
    x_1 = T37_;
    T38_ = (NU64)0;
    T38_ = len16__pureZhashes_u364(v_1.Field0, w_1.Field0, mul_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T39_ = (NU64)0;
    T39_ = shiftMix__pureZhashes_u345(y_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    T40_ = (NU64)0;
    T40_ = len16__pureZhashes_u364(v_1.Field1, w_1.Field1, mul_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result = len16__pureZhashes_u364(
        (NU64)((NU64)((NU64)((NU64)(T38_) +
                             (NU64)((NU64)((NU64)(T39_) *
                                           (NU64)(14097894508562428199ULL))))) +
               (NU64)(z_1)),
        (NU64)((NU64)(T40_) + (NU64)(x_1)), mul_1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u601)(NimStringV2 x_p0) {
  NI result;
  NU64 T1_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    if ((x_p0.len - 1) - ((NI)0) != -1 &&
        (((NI)0) < 0 || ((NI)0) >= x_p0.len || (x_p0.len - 1) < 0 ||
         (x_p0.len - 1) >= x_p0.len)) {
      raiseIndexError4(((NI)0), (x_p0.len - 1), x_p0.len);
      goto BeforeRet_;
    }
    T1_ = (NU64)0;
    T1_ = hashFarm__pureZhashes_u525(
        (((x_p0).p) ? ((NU8 *)x_p0.p->data + (((NI)0))) : NIM_NIL),
        ((x_p0.len - 1)) - (((NI)0)) + 1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result = ((NI)(T1_));
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, hash__w_u396)(NU8 *x_p0, NI x_p0Len_0) {
  NI result;
  NU64 T1_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    T1_ = (NU64)0;
    T1_ = hashFarm__pureZhashes_u525(x_p0, x_p0Len_0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result = ((NI)(T1_));
  }
BeforeRet_:;
  return result;
}
