/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw
    tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content
    tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len;
  tySequence__4eRCaZmrYLLw2k30GPTiMw_Content *p;
};
struct tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA {
  tySequence__4eRCaZmrYLLw2k30GPTiMw data;
  NI counter;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
  NI Field0;
  NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content {
  NI cap;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u259)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void,
                        newSeq__e_u92)(tySequence__4eRCaZmrYLLw2k30GPTiMw *s_p0,
                                       NI len_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1,
                                                 NI64 b_p2);
static N_INLINE(NI,
                rawGet__e_u198)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA t_p0,
                                NimStringV2 key_p1, NI *hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u601)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void *a_p0, void *b_p1,
                                                  NI size_p2);
static N_INLINE(int, nimCmpMem)(void *a_p0, void *b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1);
static N_INLINE(NIM_BOOL, mustRehash__e_u307)(
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA t_p0);
N_LIB_PRIVATE
N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          enlarge__e_u381)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *s_p0);
static N_INLINE(NI, rawGetKnownHC__e_u433)(
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA t_p0, NimStringV2 key_p1,
    NI hc_p2);
N_LIB_PRIVATE
N_NIMCALL(void,
          rawInsert__e_u490)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *s_p0,
                             tySequence__4eRCaZmrYLLw2k30GPTiMw *data_p1,
                             NimStringV2 key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2710)(NimStringV2 *dest_p0,
                                                     NimStringV2 src_p1);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___e_u269)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void *p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void *p_p0, NI align_p1);
static const struct {
  NI cap;
  NIM_CHAR data[47 + 1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_6 = {
    47 | NIM_STRLIT_FLAG, "hashcommon.nim(34, 9) `\012t.counter < t.dataLen` "};
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_7 = {
    47, (NimStrPayload *)&TM__0JXiWyhP5OCO8jWMA6sb1w_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0) {
  NI result;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_2;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_3;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0,
                  &TM__0JXiWyhP5OCO8jWMA6sb1w_2)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimAddInt((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_2), ((NI)4),
                  &TM__0JXiWyhP5OCO8jWMA6sb1w_3)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = nextPowerOfTwo__pureZmath_u259((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_3));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0) {
  NIM_BOOL result;
  result = !((hcode_p0 == ((NI)0)));
  return result;
}
static N_INLINE(int, nimCmpMem)(void *a_p0, void *b_p1, NI size_p2) {
  int result;
  result = memcmp(a_p0, b_p1, ((size_t)(size_p2)));
  return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void *a_p0, void *b_p1,
                                                  NI size_p2) {
  NIM_BOOL result;
  int T1_;
  T1_ = (int)0;
  T1_ = nimCmpMem(a_p0, b_p1, size_p2);
  result = (T1_ == ((NI32)0));
  return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
  NIM_BOOL result;
  NI alen_1;
  NI blen_1;
  {
    result = NIM_FALSE;
    alen_1 = a_p0.len;
    blen_1 = b_p1.len;
    {
      if (!(alen_1 == blen_1))
        goto LA3_;
      {
        if (!(alen_1 == ((NI)0)))
          goto LA7_;
        result = NIM_TRUE;
        goto BeforeRet_;
      }
    LA7_:;
      result = equalMem__system_u1749(((void *)((&a_p0.p->data[((NI)0)]))),
                                      ((void *)((&b_p1.p->data[((NI)0)]))),
                                      (alen_1));
      goto BeforeRet_;
    }
  LA3_:;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0,
                                                        NI maxHash_p1) {
  NI result;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_4;
  {
    if (nimAddInt(h_p0, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_4)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_4)&maxHash_p1);
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI,
                rawGet__e_u198)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA t_p0,
                                NimStringV2 key_p1, NI *hc_p2) {
  NI result;
  NI T1_;
  NI h_1;
  NI T11_;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_5;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    T1_ = (NI)0;
    T1_ = hash__pureZhashes_u601(key_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    (*hc_p2) = T1_;
    {
      if (!((*hc_p2) == ((NI)0)))
        goto LA4_;
      (*hc_p2) = ((NI)314159265);
    }
  LA4_:;
    {
      NI T8_;
      T8_ = t_p0.data.len;
      if (!(T8_ == ((NI)0)))
        goto LA9_;
      result = ((NI)-1);
      goto BeforeRet_;
    }
  LA9_:;
    T11_ = (t_p0.data.len - 1);
    h_1 = (NI)((*hc_p2) & T11_);
    {
      while (1) {
        NIM_BOOL T14_;
        NI T21_;
        if (h_1 < 0 || h_1 >= t_p0.data.len) {
          raiseIndexError2(h_1, t_p0.data.len - 1);
          goto BeforeRet_;
        }
        T14_ = (NIM_BOOL)0;
        T14_ =
            isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T14_)
          goto LA13;
        {
          NIM_BOOL T17_;
          T17_ = (NIM_BOOL)0;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
          if (!(T17_))
            goto LA18_;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
        LA18_:;
          if (!T17_)
            goto LA19_;
          result = h_1;
          goto BeforeRet_;
        }
      LA19_:;
        T21_ = (t_p0.data.len - 1);
        h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA13:;
    }
    if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_5)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_5);
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NIM_BOOL, mustRehash__e_u307)(
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA t_p0) {
  NIM_BOOL result;
  NIM_BOOL T6_;
  NI T7_;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_8;
  NI T9_;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_9;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NIM_BOOL)0;
    {
      NI T3_;
      T3_ = t_p0.data.len;
      if (!!((t_p0.counter < T3_)))
        goto LA4_;
      failedAssertImpl__stdZassertions_u234(TM__0JXiWyhP5OCO8jWMA6sb1w_7);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
    }
  LA4_:;
    T6_ = (NIM_BOOL)0;
    T7_ = t_p0.data.len;
    if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))),
                  &TM__0JXiWyhP5OCO8jWMA6sb1w_8)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T6_ = (T7_ < (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_8));
    if (T6_)
      goto LA8_;
    T9_ = t_p0.data.len;
    if (nimSubInt(T9_, t_p0.counter, &TM__0JXiWyhP5OCO8jWMA6sb1w_9)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_9) < ((NI)4));
  LA8_:;
    result = T6_;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI, rawGetKnownHC__e_u433)(
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA t_p0, NimStringV2 key_p1,
    NI hc_p2) {
  NI result;
  NI h_1;
  NI T6_;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_11;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    {
      NI T3_;
      T3_ = t_p0.data.len;
      if (!(T3_ == ((NI)0)))
        goto LA4_;
      result = ((NI)-1);
      goto BeforeRet_;
    }
  LA4_:;
    T6_ = (t_p0.data.len - 1);
    h_1 = (NI)(hc_p2 & T6_);
    {
      while (1) {
        NIM_BOOL T9_;
        NI T16_;
        if (h_1 < 0 || h_1 >= t_p0.data.len) {
          raiseIndexError2(h_1, t_p0.data.len - 1);
          goto BeforeRet_;
        }
        T9_ = (NIM_BOOL)0;
        T9_ =
            isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T9_)
          goto LA8;
        {
          NIM_BOOL T12_;
          T12_ = (NIM_BOOL)0;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
          if (!(T12_))
            goto LA13_;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
        LA13_:;
          if (!T12_)
            goto LA14_;
          result = h_1;
          goto BeforeRet_;
        }
      LA14_:;
        T16_ = (t_p0.data.len - 1);
        h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA8:;
    }
    if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_11)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_11);
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          rawInsert__e_u490)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *s_p0,
                             tySequence__4eRCaZmrYLLw2k30GPTiMw *data_p1,
                             NimStringV2 key_p2, NI hc_p3, NI h_p4) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    {
      NI T3_;
      NI correctSizeX60gensym11__1;
      T3_ = (*data_p1).len;
      if (!(T3_ == ((NI)0)))
        goto LA4_;
      correctSizeX60gensym11__1 =
          slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      (*s_p0).counter = ((NI)0);
      if ((correctSizeX60gensym11__1) < ((NI)0) ||
          (correctSizeX60gensym11__1) > ((NI)IL64(9223372036854775807))) {
        raiseRangeErrorI(correctSizeX60gensym11__1, ((NI)0),
                         ((NI)IL64(9223372036854775807)));
        goto BeforeRet_;
      }
      newSeq__e_u92((&(*s_p0).data), (correctSizeX60gensym11__1));
    }
  LA4_:;
    if (h_p4 < 0 || h_p4 >= (*data_p1).len) {
      raiseIndexError2(h_p4, (*data_p1).len - 1);
      goto BeforeRet_;
    }
    eqcopy___system_u2710((&(*data_p1).p->data[h_p4].Field1), key_p2);
    if (h_p4 < 0 || h_p4 >= (*data_p1).len) {
      raiseIndexError2(h_p4, (*data_p1).len - 1);
      goto BeforeRet_;
    }
    (*data_p1).p->data[h_p4].Field0 = hc_p3;
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___e_u269)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0) {
  NI colontmp_;
  colontmp_ = ((NI)0);
  {
    while (1) {
      NI T3_;
      T3_ = dest_p0.len;
      if (!(colontmp_ < T3_))
        goto LA2;
      if (dest_p0.p->data[colontmp_].Field1.p &&
          !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
        deallocShared(dest_p0.p->data[colontmp_].Field1.p);
      }
      colontmp_ += ((NI)1);
    }
  LA2:;
  }
  if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
    alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));
  }
}
N_LIB_PRIVATE
N_NIMCALL(void,
          enlarge__e_u381)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *s_p0) {
  tySequence__4eRCaZmrYLLw2k30GPTiMw n_1;
  NI T1_;
  NI TM__0JXiWyhP5OCO8jWMA6sb1w_10;
  tySequence__4eRCaZmrYLLw2k30GPTiMw T2_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    n_1.len = 0;
    n_1.p = NIM_NIL;
    T1_ = (*s_p0).data.len;
    if (nimMulInt(T1_, ((NI)2), &TM__0JXiWyhP5OCO8jWMA6sb1w_10)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)) < ((NI)0) ||
        ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)) >
            ((NI)IL64(9223372036854775807))) {
      raiseRangeErrorI((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10), ((NI)0),
                       ((NI)IL64(9223372036854775807)));
      goto BeforeRet_;
    }
    newSeq__e_u92((&n_1), ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)));
    T2_.len = 0;
    T2_.p = NIM_NIL;
    T2_ = (*s_p0).data;
    (*s_p0).data = n_1;
    n_1 = T2_;
    {
      NI i_1;
      NI colontmp_;
      NI T4_;
      NI res_1;
      i_1 = (NI)0;
      colontmp_ = (NI)0;
      T4_ = (n_1.len - 1);
      colontmp_ = T4_;
      res_1 = ((NI)0);
      {
        while (1) {
          NI TM__0JXiWyhP5OCO8jWMA6sb1w_13;
          if (!(res_1 <= colontmp_))
            goto LA6;
          i_1 = ((NI)(res_1));
          {
            NIM_BOOL T9_;
            NI j_1;
            NI T12_;
            NI TM__0JXiWyhP5OCO8jWMA6sb1w_12;
            tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *T13_;
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            T9_ = (NIM_BOOL)0;
            T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
            if (!T9_)
              goto LA10_;
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            T12_ = (NI)0;
            T12_ = rawGetKnownHC__e_u433((*s_p0), n_1.p->data[i_1].Field1,
                                         n_1.p->data[i_1].Field0);
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
            if (nimSubInt(((NI)-1), T12_, &TM__0JXiWyhP5OCO8jWMA6sb1w_12)) {
              raiseOverflow();
              goto BeforeRet_;
            };
            j_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_12);
            T13_ = (tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *)0;
            T13_ = s_p0;
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            rawInsert__e_u490(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1,
                              n_1.p->data[i_1].Field0, j_1);
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
          }
        LA10_:;
          if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_13)) {
            raiseOverflow();
            goto BeforeRet_;
          };
          res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13);
        }
      LA6:;
      }
    }
    eqdestroy___e_u269(n_1);
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(void, incl__e_u57)(tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *s_p0,
                             NimStringV2 key_p1) {
  NI hc_1;
  NI index_1;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    {
      NI T3_;
      NI correctSizeX60gensym2__1;
      T3_ = (*s_p0).data.len;
      if (!(T3_ == ((NI)0)))
        goto LA4_;
      correctSizeX60gensym2__1 =
          slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      (*s_p0).counter = ((NI)0);
      if ((correctSizeX60gensym2__1) < ((NI)0) ||
          (correctSizeX60gensym2__1) > ((NI)IL64(9223372036854775807))) {
        raiseRangeErrorI(correctSizeX60gensym2__1, ((NI)0),
                         ((NI)IL64(9223372036854775807)));
        goto BeforeRet_;
      }
      newSeq__e_u92((&(*s_p0).data), (correctSizeX60gensym2__1));
    }
  LA4_:;
    hc_1 = (NI)0;
    index_1 = rawGet__e_u198((*s_p0), key_p1, (&hc_1));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    {
      tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *T15_;
      NI TM__0JXiWyhP5OCO8jWMA6sb1w_14;
      NI TM__0JXiWyhP5OCO8jWMA6sb1w_15;
      if (!(index_1 < ((NI)0)))
        goto LA8_;
      {
        NIM_BOOL T12_;
        T12_ = (NIM_BOOL)0;
        T12_ = mustRehash__e_u307((*s_p0));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T12_)
          goto LA13_;
        enlarge__e_u381(s_p0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        index_1 = rawGetKnownHC__e_u433((*s_p0), key_p1, hc_1);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA13_:;
      T15_ = (tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *)0;
      T15_ = s_p0;
      if (nimSubInt(((NI)-1), index_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_14)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      rawInsert__e_u490(T15_, (&(*s_p0).data), key_p1, hc_1,
                        (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_14));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      if (nimAddInt((*s_p0).counter, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_15)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      (*s_p0).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_15);
    }
  LA8_:;
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___e_u775)(
    tyObject_HashSet__Q79bJCQlS4a4xFp5NpFwgKA *dest_p0) {
  eqdestroy___e_u269((*dest_p0).data);
}
