/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ
    tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ;
typedef struct tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA
    tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__589aIoFuYV9awMG68GXzrKTA
    tySequence__589aIoFuYV9awMG68GXzrKTA;
typedef struct tySequence__589aIoFuYV9awMG68GXzrKTA_Content
    tySequence__589aIoFuYV9awMG68GXzrKTA_Content;
typedef struct tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ
    tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ;
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct TNimTypeV2 {
  void *destructor;
  NI size;
  NI16 align;
  NI16 depth;
  NU32 *display;
  void *traceImpl;
  void *typeInfoV1;
  NI flags;
  void *vTable[SEQ_DECL_SIZE];
};
struct RootObj {
  TNimTypeV2 *m_type;
};
struct tySequence__589aIoFuYV9awMG68GXzrKTA {
  NI len;
  tySequence__589aIoFuYV9awMG68GXzrKTA_Content *p;
};
struct Exception {
  RootObj Sup;
  Exception *parent;
  NCSTRING name;
  NimStringV2 message;
  tySequence__589aIoFuYV9awMG68GXzrKTA trace;
  Exception *up;
};
struct tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA {
  Exception Sup;
};
struct tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ {
  tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA Sup;
};
struct tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ {
  NCSTRING procname;
  NI line;
  NCSTRING filename;
};
struct tySequence__589aIoFuYV9awMG68GXzrKTA_Content {
  NI cap;
  tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOINLINE(void,
                         raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0);
static N_INLINE(void, sysFatal__stdZassertions_u28)(NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void *, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2713)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void,
                        raiseExceptionEx)(Exception *e_p0, NCSTRING ename_p1,
                                          NCSTRING procname_p2,
                                          NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
extern TNimTypeV2 NTIv2__Y9cUA9aL9bNkt2NfB9b0L9carwQ_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static N_INLINE(void, sysFatal__stdZassertions_u28)(NimStringV2 message_p1) {
  NimStringV2 colontmpD_;
  tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *T1_;
  {
    colontmpD_.len = 0;
    colontmpD_.p = NIM_NIL;
    T1_ = NIM_NIL;
    T1_ = (tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *)nimNewObj(
        sizeof(tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ),
        NIM_ALIGNOF(tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ));
    (*T1_).Sup.Sup.Sup.m_type = (&NTIv2__Y9cUA9aL9bNkt2NfB9b0L9carwQ_);
    (*T1_).Sup.Sup.name = "AssertionDefect";
    colontmpD_ = eqdup___system_u2713(message_p1);
    (*T1_).Sup.Sup.message = colontmpD_;
    raiseExceptionEx((Exception *)T1_, "AssertionDefect", "sysFatal",
                     "fatal.nim", 53);
    goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
N_LIB_PRIVATE N_NOINLINE(void,
                         raiseAssert__stdZassertions_u26)(NimStringV2 msg_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    sysFatal__stdZassertions_u28(msg_p0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    raiseAssert__stdZassertions_u26(msg_p0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
