/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
N_LIB_PRIVATE
N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2 *result_p0,
                                                      NI64 x_p1);
static N_INLINE(void,
                addInt__stdZprivateZdigitsutils_u204)(NimStringV2 *result_p0,
                                                      NI x_p1);
static const struct {
  NI cap;
  NIM_CHAR data[0 + 1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_2 = {0 | NIM_STRLIT_FLAG, ""};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = {
    0, (NimStrPayload *)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {
    0, (NimStrPayload *)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = {
    0, (NimStrPayload *)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static N_INLINE(void,
                addInt__stdZprivateZdigitsutils_u204)(NimStringV2 *result_p0,
                                                      NI x_p1) {
  addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64)(x_p1)));
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2,
                        dollar___systemZdollars_u14)(NI xX60gensym0__p0) {
  NimStringV2 result;
  result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_4;
  addInt__stdZprivateZdigitsutils_u204((&result), xX60gensym0__p0);
  return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2,
                        dollar___systemZdollars_u34)(NI64 xX60gensym4__p0) {
  NimStringV2 result;
  result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
  addInt__stdZprivateZdigitsutils_u187((&result), xX60gensym4__p0);
  return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2,
                        dollar___systemZdollars_u29)(NI32 xX60gensym3__p0) {
  NimStringV2 result;
  result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_5;
  addInt__stdZprivateZdigitsutils_u204((&result), ((NI)(xX60gensym3__p0)));
  return result;
}
