/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
  NI Field0;
  NimStringV2 Field1;
};
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void *p_p0);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u1078)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw *dest_p0) {
  if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Field1.p);
  }
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___w_u1075)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw *dest_p0) {
  (*dest_p0).Field0 = 0;
  (*dest_p0).Field1.len = 0;
  (*dest_p0).Field1.p = NIM_NIL;
}
