/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w
    tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w;
typedef struct tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA;
typedef struct tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA
    tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__589aIoFuYV9awMG68GXzrKTA
    tySequence__589aIoFuYV9awMG68GXzrKTA;
typedef struct tySequence__589aIoFuYV9awMG68GXzrKTA_Content
    tySequence__589aIoFuYV9awMG68GXzrKTA_Content;
typedef struct tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg
    tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg;
typedef struct tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw
    tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q
    tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA
    tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA;
typedef struct tyTuple__n2s9chmKZxsUwRqu6DJsQeg
    tyTuple__n2s9chmKZxsUwRqu6DJsQeg;
typedef struct tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ
    tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ;
typedef struct tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ
    tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ;
typedef struct tyObject_ArithmeticDefect__zlsRU12V3rET9b7Z9cjiANeg
    tyObject_ArithmeticDefect__zlsRU12V3rET9b7Z9cjiANeg;
typedef struct tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ
    tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ;
typedef struct tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A
    tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A;
typedef struct tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ
    tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ;
struct TNimTypeV2 {
  void *destructor;
  NI size;
  NI16 align;
  NI16 depth;
  NU32 *display;
  void *traceImpl;
  void *typeInfoV1;
  NI flags;
  void *vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA {
  NI rc;
  NI rootIdx;
};
struct RootObj {
  TNimTypeV2 *m_type;
};
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tySequence__589aIoFuYV9awMG68GXzrKTA {
  NI len;
  tySequence__589aIoFuYV9awMG68GXzrKTA_Content *p;
};
struct Exception {
  RootObj Sup;
  Exception *parent;
  NCSTRING name;
  NimStringV2 message;
  tySequence__589aIoFuYV9awMG68GXzrKTA trace;
  Exception *up;
};
struct tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA {
  Exception Sup;
};
struct tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w {
  tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA Sup;
};
struct tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw {
  NI len;
  NI cap;
  tyTuple__N4J9cV4JZGem3ljqqj5rT0Q *d;
};
struct tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA {
  NI len;
  NI cap;
  tyTuple__n2s9chmKZxsUwRqu6DJsQeg *d;
};
struct tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg {
  tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw traceStack;
  tyObject_CellSeq__XlVmMtcklrxD8fn9aty9cBWA toFree;
  NI freed;
  NI touched;
  NI edges;
  NI rcSum;
  NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
  void **Field0;
  TNimTypeV2 *Field1;
};
struct tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ {
  tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA Sup;
};
struct tyObject_ArithmeticDefect__zlsRU12V3rET9b7Z9cjiANeg {
  tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA Sup;
};
struct tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ {
  tyObject_ArithmeticDefect__zlsRU12V3rET9b7Z9cjiANeg Sup;
};
struct tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ {
  tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA Sup;
};
struct tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A {
  tyObject_Defect__Wu9bNb861IhvMWLNgjkQdgA Sup;
};
struct tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ {
  NCSTRING procname;
  NI line;
  NCSTRING filename;
};
struct tySequence__589aIoFuYV9awMG68GXzrKTA_Content {
  NI cap;
  tyObject_StackTraceEntry__SUt0nvJeHzkOjZMmUMvbgQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u56)(void *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4636)(
    tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w *dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void *p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3482)(
    NIM_BOOL isDestroyAction_p0,
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *s_p1, TNimTypeV2 *desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void *p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u74)(
    tySequence__589aIoFuYV9awMG68GXzrKTA dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void *p_p0);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4648)(
    tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w *dest_p0, void *env_p1);
static N_INLINE(void, nimTraceRefDyn)(void *q_p0, void *env_p1);
static N_INLINE(void, add__system_u3022)(
    tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw *s_p0, void **c_p1,
    TNimTypeV2 *t_p2);
N_LIB_PRIVATE
N_NIMCALL(void,
          resize__system_u3030)(tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw *s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u60)(void *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4705)(
    tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4717)(
    tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ *dest_p0, void *env_p1);
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u62)(void *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5109)(
    tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5121)(
    tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ *dest_p0, void *env_p1);
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u64)(void *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u35)(
    tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u47)(
    tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *dest_p0,
    void *env_p1);
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u66)(void *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4795)(
    tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A *dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4807)(
    tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A *dest_p0, void *env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__hx0kfJHKDXw5JgJDoSTe7w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__GdEruFfm7a9bNp3DWxTaGoQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__vF2UD6tw1qKGWLj2lYPGOQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Y9cUA9aL9bNkt2NfB9b0L9carwQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__wvkJafp9bQP7ART9aEmn2X6A_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[4] = {
    3701606400, 1285336064, 4019023616, 488930304};
N_LIB_PRIVATE TNimTypeV2 NTIv2__hx0kfJHKDXw5JgJDoSTe7w_ = {
    .destructor = (void *)rttiDestroy__systemZexceptions_u56,
    .size = sizeof(tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w),
    .align = (NI16)NIM_ALIGNOF(tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w),
    .depth = 3,
    .display = TM__TzI3paKQY09cLjc9cmCvur3A_2,
    .traceImpl = (void *)eqtrace___system_u4648,
    .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {
    3701606400, 1285336064, 4019023616, 3509303296};
N_LIB_PRIVATE TNimTypeV2 NTIv2__GdEruFfm7a9bNp3DWxTaGoQ_ = {
    .destructor = (void *)rttiDestroy__systemZexceptions_u60,
    .size = sizeof(tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ),
    .align = (NI16)NIM_ALIGNOF(tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ),
    .depth = 3,
    .display = TM__TzI3paKQY09cLjc9cmCvur3A_3,
    .traceImpl = (void *)eqtrace___system_u4717,
    .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[5] = {
    3701606400, 1285336064, 4019023616, 1527862016, 1569984256};
N_LIB_PRIVATE TNimTypeV2 NTIv2__vF2UD6tw1qKGWLj2lYPGOQ_ = {
    .destructor = (void *)rttiDestroy__systemZexceptions_u62,
    .size = sizeof(tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ),
    .align = (NI16)NIM_ALIGNOF(tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ),
    .depth = 4,
    .display = TM__TzI3paKQY09cLjc9cmCvur3A_4,
    .traceImpl = (void *)eqtrace___system_u5121,
    .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {
    3701606400, 1285336064, 4019023616, 4110480384};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Y9cUA9aL9bNkt2NfB9b0L9carwQ_ = {
    .destructor = (void *)rttiDestroy__systemZexceptions_u64,
    .size = sizeof(tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ),
    .align = (NI16)NIM_ALIGNOF(
        tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ),
    .depth = 3,
    .display = TM__TzI3paKQY09cLjc9cmCvur3A_5,
    .traceImpl = (void *)eqtrace___stdZassertions_u47,
    .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {
    3701606400, 1285336064, 4019023616, 4178143488};
N_LIB_PRIVATE TNimTypeV2 NTIv2__wvkJafp9bQP7ART9aEmn2X6A_ = {
    .destructor = (void *)rttiDestroy__systemZexceptions_u66,
    .size = sizeof(tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A),
    .align = (NI16)NIM_ALIGNOF(tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A),
    .depth = 3,
    .display = TM__TzI3paKQY09cLjc9cmCvur3A_6,
    .traceImpl = (void *)eqtrace___system_u4807,
    .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
  NI result;
  result = ((NI)((NU)((NU64)(((NU)(x_p0))) - (NU64)(((NU)(y_p1))))));
  return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void *p_p0) {
  NIM_BOOL result;
  result = NIM_FALSE;
  {
    tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *cell_1;
    NI T5_;
    if (!!((p_p0 == NIM_NIL)))
      goto LA3_;
    T5_ = (NI)0;
    T5_ = minuspercent___system_u813(((NI)(ptrdiff_t)(p_p0)), ((NI)16));
    cell_1 = ((tyObject_RefHeader__2xCofG3B3ETP6feZxDBmFA *)(T5_));
    {
      if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0)))
        goto LA8_;
      result = NIM_TRUE;
    }
    goto LA6_;
  LA8_:;
    {
      (*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
    }
  LA6_:;
    rememberCycle__system_u3482(result, cell_1, (*((TNimTypeV2 **)(p_p0))));
  }
LA3_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4636)(
    tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w *dest_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
    if (!T3_)
      goto LA4_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
  }
LA4_:;
  eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
  if ((*dest_p0).Sup.Sup.message.p &&
      !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Sup.Sup.message.p);
  }
  {
    NIM_BOOL T8_;
    T8_ = (NIM_BOOL)0;
    T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
    if (!T8_)
      goto LA9_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
  }
LA9_:;
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u56)(void *dest_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    eqdestroy___system_u4636(
        ((tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w *)(dest_p0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
  NI result;
  result = ((NI)((NU)((NU64)(((NU)(x_p0))) + (NU64)(((NU)(y_p1))))));
  return result;
}
static N_INLINE(void, add__system_u3022)(
    tyObject_CellSeq__1kxoBNxzd1HmSvlG34IhIw *s_p0, void **c_p1,
    TNimTypeV2 *t_p2) {
  void **colontmp_;
  TNimTypeV2 *colontmp__2;
  {
    if (!((*s_p0).cap <= (*s_p0).len))
      goto LA3_;
    resize__system_u3030(s_p0);
  }
LA3_:;
  colontmp_ = c_p1;
  colontmp__2 = t_p2;
  (*s_p0).d[(*s_p0).len].Field0 = colontmp_;
  (*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
  (*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRefDyn)(void *q_p0, void *env_p1) {
  void **p_1;
  p_1 = ((void **)(q_p0));
  {
    tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg *j_1;
    if (!!(((*p_1) == NIM_NIL)))
      goto LA3_;
    j_1 = ((tyObject_GcEnv__UOdRTNAvVrYUKNl4wKuscg *)(env_p1));
    add__system_u3022((&(*j_1).traceStack), p_1, (*((TNimTypeV2 **)((*p_1)))));
  }
LA3_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4648)(
    tyObject_RangeDefect__hx0kfJHKDXw5JgJDoSTe7w *dest_p0, void *env_p1) {
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4705)(
    tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ *dest_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
    if (!T3_)
      goto LA4_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
  }
LA4_:;
  eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
  if ((*dest_p0).Sup.Sup.message.p &&
      !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Sup.Sup.message.p);
  }
  {
    NIM_BOOL T8_;
    T8_ = (NIM_BOOL)0;
    T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
    if (!T8_)
      goto LA9_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
  }
LA9_:;
}
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u60)(void *dest_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    eqdestroy___system_u4705(
        ((tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ *)(dest_p0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4717)(
    tyObject_IndexDefect__GdEruFfm7a9bNp3DWxTaGoQ *dest_p0, void *env_p1) {
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5109)(
    tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ *dest_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
    if (!T3_)
      goto LA4_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
  }
LA4_:;
  eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
  if ((*dest_p0).Sup.Sup.Sup.message.p &&
      !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
  }
  {
    NIM_BOOL T8_;
    T8_ = (NIM_BOOL)0;
    T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
    if (!T8_)
      goto LA9_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
  }
LA9_:;
}
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u62)(void *dest_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    eqdestroy___system_u5109(
        ((tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ *)(dest_p0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5121)(
    tyObject_OverflowDefect__vF2UD6tw1qKGWLj2lYPGOQ *dest_p0, void *env_p1) {
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u35)(
    tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *dest_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
    if (!T3_)
      goto LA4_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
  }
LA4_:;
  eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
  if ((*dest_p0).Sup.Sup.message.p &&
      !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Sup.Sup.message.p);
  }
  {
    NIM_BOOL T8_;
    T8_ = (NIM_BOOL)0;
    T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
    if (!T8_)
      goto LA9_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
  }
LA9_:;
}
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u64)(void *dest_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    eqdestroy___stdZassertions_u35(
        ((tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *)(dest_p0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u47)(
    tyObject_AssertionDefect__Y9cUA9aL9bNkt2NfB9b0L9carwQ *dest_p0,
    void *env_p1) {
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4795)(
    tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A *dest_p0) {
  {
    NIM_BOOL T3_;
    T3_ = (NIM_BOOL)0;
    T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
    if (!T3_)
      goto LA4_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
  }
LA4_:;
  eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
  if ((*dest_p0).Sup.Sup.message.p &&
      !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Sup.Sup.message.p);
  }
  {
    NIM_BOOL T8_;
    T8_ = (NIM_BOOL)0;
    T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
    if (!T8_)
      goto LA9_;
    nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
  }
LA9_:;
}
N_LIB_PRIVATE N_NIMCALL(void,
                        rttiDestroy__systemZexceptions_u66)(void *dest_p0) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    eqdestroy___system_u4795(
        ((tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A *)(dest_p0)));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4807)(
    tyObject_FieldDefect__wvkJafp9bQP7ART9aEmn2X6A *dest_p0, void *env_p1) {
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
  nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
