/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Table__VXRlZVRc73Y2yFgFbVYXng
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og
    tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content
    tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ
    tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw
    tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw;
typedef struct tySequence__gTwrrlHWmZAujkkSb6c2Wg
    tySequence__gTwrrlHWmZAujkkSb6c2Wg;
typedef struct tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content
    tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content
    tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyTuple__PCiVg29bAs9cXcHeoQrt1xeA
    tyTuple__PCiVg29bAs9cXcHeoQrt1xeA;
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len;
  tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content *p;
};
struct tyObject_Table__VXRlZVRc73Y2yFgFbVYXng {
  tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
  NI counter;
};
struct NimStrPayload {
  NI cap;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
  NI len;
  NimStrPayload *p;
};
struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
  NI Field0;
  NimStringV2 Field1;
  NI Field2;
};
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
  NimStringV2 Field0;
  NI Field1;
};
struct tySequence__gTwrrlHWmZAujkkSb6c2Wg {
  NI len;
  tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content *p;
};
struct tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw {
  tySequence__gTwrrlHWmZAujkkSb6c2Wg data;
  NI counter;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content *p;
};
struct tyTuple__PCiVg29bAs9cXcHeoQrt1xeA {
  NI Field0;
  tySequence__6H5Oh5UUvVCLiakt9aTwtUQ Field1;
  NI Field2;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content {
  NI cap;
  tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence__gTwrrlHWmZAujkkSb6c2Wg_Content {
  NI cap;
  tyTuple__PCiVg29bAs9cXcHeoQrt1xeA data[SEQ_DECL_SIZE];
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content {
  NI cap;
  NU8 data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2);
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng,
                        initTable__w_u1391)(NI initialSize_p0);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u259)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1,
                                                 NI64 b_p2);
N_LIB_PRIVATE
N_NIMCALL(void, newSeq__w_u1405)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og *s_p0,
                                 NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void *p_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE
N_NIMCALL(void,
          X5BX5Deq___w_u1637)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *t_p0,
                              NimStringV2 key_p1, NI val_p2);
static N_INLINE(NI,
                rawGet__w_u1697)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng t_p0,
                                 NimStringV2 key_p1, NI *hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u601)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void *a_p0, void *b_p1,
                                                  NI size_p2);
static N_INLINE(int, nimCmpMem)(void *a_p0, void *b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0,
                                                          NI maxHash_p1);
static N_INLINE(NIM_BOOL, mustRehash__w_u2024)(
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng t_p0);
N_LIB_PRIVATE
N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE
N_NIMCALL(void, enlarge__w_u2167)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *t_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          rawInsert__w_u2455)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *t_p0,
                              tySequence__pUxI6Ljo6IKKHXKOZkQ7Og *data_p1,
                              NimStringV2 key_p2, NI val_p3, NI hc_p4, NI h_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2710)(NimStringV2 *dest_p0,
                                                     NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2707)(NimStringV2 *dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1547)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void *p_p0, NI align_p1);
static N_INLINE(NI, rawGetKnownHC__w_u2612)(
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng t_p0, NimStringV2 key_p1, NI hc_p2);
static N_INLINE(NI,
                rawGet__w_u389)(tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw t_p0,
                                tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1,
                                NI *hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__w_u396)(NU8 *x_p0, NI x_p0Len_0);
N_LIB_PRIVATE
    N_NIMCALL(NIM_BOOL,
              eqeq___w_u598)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0,
                             tySequence__6H5Oh5UUvVCLiakt9aTwtUQ y_p1);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u701)(tySequence__gTwrrlHWmZAujkkSb6c2Wg dest_p0);
N_LIB_PRIVATE
N_NIMCALL(void, eqdestroy___w_u42)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
static const struct {
  NI cap;
  NIM_CHAR data[47 + 1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_6 = {
    47 | NIM_STRLIT_FLAG, "hashcommon.nim(34, 9) `\012t.counter < t.dataLen` "};
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_7 = {
    47, (NimStrPayload *)&TM__4SoG2KRQy3oMm9aUzSLtGrA_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4361;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void *a_p0, int v_p1,
                                                   NI size_p2) {
  void *T1_;
  T1_ = (void *)0;
  T1_ = memset(a_p0, v_p1, ((size_t)(size_p2)));
}
static N_INLINE(NIM_BOOL *, nimErrorFlag)(void) {
  NIM_BOOL *result;
  result = (&nimInErrorMode__system_u4361);
  return result;
}
static N_INLINE(void, nimZeroMem)(void *p_p0, NI size_p1) {
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0) {
  NI result;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0,
                  &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (nimAddInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2), ((NI)4),
                  &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result =
        nextPowerOfTwo__pureZmath_u259((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1483)(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ *dest_p0) {
  if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
    deallocShared((*dest_p0).Field1.p);
  }
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqwasMoved___w_u1480)(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ *dest_p0) {
  (*dest_p0).Field0 = 0;
  (*dest_p0).Field1.len = 0;
  (*dest_p0).Field1.p = NIM_NIL;
  (*dest_p0).Field2 = 0;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng,
                        initTable__w_u1391)(NI initialSize_p0) {
  tyObject_Table__VXRlZVRc73Y2yFgFbVYXng result;
  NI correctSizeX60gensym13__1;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result),
               sizeof(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng));
    if ((initialSize_p0) < ((NI)0) ||
        (initialSize_p0) > ((NI)IL64(9223372036854775807))) {
      raiseRangeErrorI(initialSize_p0, ((NI)0),
                       ((NI)IL64(9223372036854775807)));
      goto BeforeRet_;
    }
    correctSizeX60gensym13__1 =
        slotsNeeded__pureZcollectionsZtables_u42((initialSize_p0));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    result.counter = ((NI)0);
    if ((correctSizeX60gensym13__1) < ((NI)0) ||
        (correctSizeX60gensym13__1) > ((NI)IL64(9223372036854775807))) {
      raiseRangeErrorI(correctSizeX60gensym13__1, ((NI)0),
                       ((NI)IL64(9223372036854775807)));
      goto BeforeRet_;
    }
    newSeq__w_u1405((&result.data), (correctSizeX60gensym13__1));
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
  NIM_BOOL result;
  result = !((hcode_p0 == ((NI)0)));
  return result;
}
static N_INLINE(int, nimCmpMem)(void *a_p0, void *b_p1, NI size_p2) {
  int result;
  result = memcmp(a_p0, b_p1, ((size_t)(size_p2)));
  return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void *a_p0, void *b_p1,
                                                  NI size_p2) {
  NIM_BOOL result;
  int T1_;
  T1_ = (int)0;
  T1_ = nimCmpMem(a_p0, b_p1, size_p2);
  result = (T1_ == ((NI32)0));
  return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
  NIM_BOOL result;
  NI alen_1;
  NI blen_1;
  {
    result = NIM_FALSE;
    alen_1 = a_p0.len;
    blen_1 = b_p1.len;
    {
      if (!(alen_1 == blen_1))
        goto LA3_;
      {
        if (!(alen_1 == ((NI)0)))
          goto LA7_;
        result = NIM_TRUE;
        goto BeforeRet_;
      }
    LA7_:;
      result = equalMem__system_u1749(((void *)((&a_p0.p->data[((NI)0)]))),
                                      ((void *)((&b_p1.p->data[((NI)0)]))),
                                      (alen_1));
      goto BeforeRet_;
    }
  LA3_:;
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0,
                                                          NI maxHash_p1) {
  NI result;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;
  {
    if (nimAddInt(h_p0, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4)&maxHash_p1);
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI,
                rawGet__w_u1697)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng t_p0,
                                 NimStringV2 key_p1, NI *hc_p2) {
  NI result;
  NI T1_;
  NI h_1;
  NI T11_;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_5;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    T1_ = (NI)0;
    T1_ = hash__pureZhashes_u601(key_p1);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    (*hc_p2) = T1_;
    {
      if (!((*hc_p2) == ((NI)0)))
        goto LA4_;
      (*hc_p2) = ((NI)314159265);
    }
  LA4_:;
    {
      NI T8_;
      T8_ = t_p0.data.len;
      if (!(T8_ == ((NI)0)))
        goto LA9_;
      result = ((NI)-1);
      goto BeforeRet_;
    }
  LA9_:;
    T11_ = (t_p0.data.len - 1);
    h_1 = (NI)((*hc_p2) & T11_);
    {
      while (1) {
        NIM_BOOL T14_;
        NI T21_;
        if (h_1 < 0 || h_1 >= t_p0.data.len) {
          raiseIndexError2(h_1, t_p0.data.len - 1);
          goto BeforeRet_;
        }
        T14_ = (NIM_BOOL)0;
        T14_ = isFilled__pureZcollectionsZtables_u31(
            t_p0.data.p->data[h_1].Field0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T14_)
          goto LA13;
        {
          NIM_BOOL T17_;
          T17_ = (NIM_BOOL)0;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
          if (!(T17_))
            goto LA18_;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
        LA18_:;
          if (!T17_)
            goto LA19_;
          result = h_1;
          goto BeforeRet_;
        }
      LA19_:;
        T21_ = (t_p0.data.len - 1);
        h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA13:;
    }
    if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_5)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_5);
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NIM_BOOL, mustRehash__w_u2024)(
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng t_p0) {
  NIM_BOOL result;
  NIM_BOOL T6_;
  NI T7_;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_8;
  NI T9_;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_9;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NIM_BOOL)0;
    {
      NI T3_;
      T3_ = t_p0.data.len;
      if (!!((t_p0.counter < T3_)))
        goto LA4_;
      failedAssertImpl__stdZassertions_u234(TM__4SoG2KRQy3oMm9aUzSLtGrA_7);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
    }
  LA4_:;
    T6_ = (NIM_BOOL)0;
    T7_ = t_p0.data.len;
    if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))),
                  &TM__4SoG2KRQy3oMm9aUzSLtGrA_8)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T6_ = (T7_ < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_8));
    if (T6_)
      goto LA8_;
    T9_ = t_p0.data.len;
    if (nimSubInt(T9_, t_p0.counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_9)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_9) < ((NI)4));
  LA8_:;
    result = T6_;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__w_u2455)(
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *t_p0,
    tySequence__pUxI6Ljo6IKKHXKOZkQ7Og *data_p1, NimStringV2 key_p2, NI val_p3,
    NI hc_p4, NI h_p5) {
  {
    if (h_p5 < 0 || h_p5 >= (*data_p1).len) {
      raiseIndexError2(h_p5, (*data_p1).len - 1);
      goto BeforeRet_;
    }
    eqcopy___system_u2710((&(*data_p1).p->data[h_p5].Field1), key_p2);
    if (h_p5 < 0 || h_p5 >= (*data_p1).len) {
      raiseIndexError2(h_p5, (*data_p1).len - 1);
      goto BeforeRet_;
    }
    (*data_p1).p->data[h_p5].Field2 = val_p3;
    if (h_p5 < 0 || h_p5 >= (*data_p1).len) {
      raiseIndexError2(h_p5, (*data_p1).len - 1);
      goto BeforeRet_;
    }
    (*data_p1).p->data[h_p5].Field0 = hc_p4;
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u1547)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og dest_p0) {
  NI colontmp_;
  colontmp_ = ((NI)0);
  {
    while (1) {
      NI T3_;
      T3_ = dest_p0.len;
      if (!(colontmp_ < T3_))
        goto LA2;
      if (dest_p0.p->data[colontmp_].Field1.p &&
          !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
        deallocShared(dest_p0.p->data[colontmp_].Field1.p);
      }
      colontmp_ += ((NI)1);
    }
  LA2:;
  }
  if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
    alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ));
  }
}
N_LIB_PRIVATE
N_NIMCALL(void,
          enlarge__w_u2167)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *t_p0) {
  tySequence__pUxI6Ljo6IKKHXKOZkQ7Og n_1;
  NI T1_;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_10;
  tySequence__pUxI6Ljo6IKKHXKOZkQ7Og T2_;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    n_1.len = 0;
    n_1.p = NIM_NIL;
    T1_ = (*t_p0).data.len;
    if (nimMulInt(T1_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) < ((NI)0) ||
        ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) >
            ((NI)IL64(9223372036854775807))) {
      raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10), ((NI)0),
                       ((NI)IL64(9223372036854775807)));
      goto BeforeRet_;
    }
    newSeq__w_u1405((&n_1), ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)));
    T2_.len = 0;
    T2_.p = NIM_NIL;
    T2_ = (*t_p0).data;
    (*t_p0).data = n_1;
    n_1 = T2_;
    {
      NI i_1;
      NI colontmp_;
      NI T4_;
      NI res_1;
      i_1 = (NI)0;
      colontmp_ = (NI)0;
      T4_ = (n_1.len - 1);
      colontmp_ = T4_;
      res_1 = ((NI)0);
      {
        while (1) {
          NI eh_1;
          NI TM__4SoG2KRQy3oMm9aUzSLtGrA_11;
          if (!(res_1 <= colontmp_))
            goto LA6;
          i_1 = ((NI)(res_1));
          if (i_1 < 0 || i_1 >= n_1.len) {
            raiseIndexError2(i_1, n_1.len - 1);
            goto BeforeRet_;
          }
          eh_1 = n_1.p->data[i_1].Field0;
          {
            NIM_BOOL T9_;
            NimStringV2 colontmpD_;
            NI j_1;
            NI T12_;
            tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *T17_;
            NI T18_;
            T9_ = (NIM_BOOL)0;
            T9_ = isFilled__pureZcollectionsZtables_u31(eh_1);
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
            if (!T9_)
              goto LA10_;
            colontmpD_.len = 0;
            colontmpD_.p = NIM_NIL;
            T12_ = ((*t_p0).data.len - 1);
            j_1 = (NI)(eh_1 & T12_);
            {
              while (1) {
                NIM_BOOL T15_;
                NI T16_;
                if (j_1 < 0 || j_1 >= (*t_p0).data.len) {
                  raiseIndexError2(j_1, (*t_p0).data.len - 1);
                  goto BeforeRet_;
                }
                T15_ = (NIM_BOOL)0;
                T15_ = isFilled__pureZcollectionsZtables_u31(
                    (*t_p0).data.p->data[j_1].Field0);
                if (NIM_UNLIKELY(*nimErr_))
                  goto BeforeRet_;
                if (!T15_)
                  goto LA14;
                T16_ = ((*t_p0).data.len - 1);
                j_1 = nextTry__pureZcollectionsZtables_u34(j_1, T16_);
                if (NIM_UNLIKELY(*nimErr_))
                  goto BeforeRet_;
              }
            LA14:;
            }
            T17_ = (tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *)0;
            T17_ = t_p0;
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            colontmpD_ = n_1.p->data[i_1].Field1;
            eqwasMoved___system_u2707((&n_1.p->data[i_1].Field1));
            if (i_1 < 0 || i_1 >= n_1.len) {
              raiseIndexError2(i_1, n_1.len - 1);
              goto BeforeRet_;
            }
            T18_ = (NI)0;
            T18_ = n_1.p->data[i_1].Field2;
            n_1.p->data[i_1].Field2 = 0;
            rawInsert__w_u2455(T17_, (&(*t_p0).data), colontmpD_, T18_, eh_1,
                               j_1);
            if (NIM_UNLIKELY(*nimErr_))
              goto BeforeRet_;
            if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
              deallocShared(colontmpD_.p);
            }
          }
        LA10_:;
          if (nimAddInt(res_1, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_11)) {
            raiseOverflow();
            goto BeforeRet_;
          };
          res_1 = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_11);
        }
      LA6:;
      }
    }
    eqdestroy___w_u1547(n_1);
  }
BeforeRet_:;
}
static N_INLINE(NI, rawGetKnownHC__w_u2612)(
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng t_p0, NimStringV2 key_p1, NI hc_p2) {
  NI result;
  NI h_1;
  NI T6_;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    {
      NI T3_;
      T3_ = t_p0.data.len;
      if (!(T3_ == ((NI)0)))
        goto LA4_;
      result = ((NI)-1);
      goto BeforeRet_;
    }
  LA4_:;
    T6_ = (t_p0.data.len - 1);
    h_1 = (NI)(hc_p2 & T6_);
    {
      while (1) {
        NIM_BOOL T9_;
        NI T16_;
        if (h_1 < 0 || h_1 >= t_p0.data.len) {
          raiseIndexError2(h_1, t_p0.data.len - 1);
          goto BeforeRet_;
        }
        T9_ = (NIM_BOOL)0;
        T9_ = isFilled__pureZcollectionsZtables_u31(
            t_p0.data.p->data[h_1].Field0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T9_)
          goto LA8;
        {
          NIM_BOOL T12_;
          T12_ = (NIM_BOOL)0;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
          if (!(T12_))
            goto LA13_;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
        LA13_:;
          if (!T12_)
            goto LA14_;
          result = h_1;
          goto BeforeRet_;
        }
      LA14_:;
        T16_ = (t_p0.data.len - 1);
        h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T16_);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA8:;
    }
    if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12);
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          X5BX5Deq___w_u1637)(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *t_p0,
                              NimStringV2 key_p1, NI val_p2) {
  NI hc_1;
  NI index_1;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    {
      NI T3_;
      NI correctSizeX60gensym16__1;
      T3_ = (*t_p0).data.len;
      if (!(T3_ == ((NI)0)))
        goto LA4_;
      correctSizeX60gensym16__1 =
          slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      (*t_p0).counter = ((NI)0);
      if ((correctSizeX60gensym16__1) < ((NI)0) ||
          (correctSizeX60gensym16__1) > ((NI)IL64(9223372036854775807))) {
        raiseRangeErrorI(correctSizeX60gensym16__1, ((NI)0),
                         ((NI)IL64(9223372036854775807)));
        goto BeforeRet_;
      }
      newSeq__w_u1405((&(*t_p0).data), (correctSizeX60gensym16__1));
    }
  LA4_:;
    hc_1 = 0;
    index_1 = rawGet__w_u1697((*t_p0), key_p1, (&hc_1));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    {
      if (!(((NI)0) <= index_1))
        goto LA8_;
      if (index_1 < 0 || index_1 >= (*t_p0).data.len) {
        raiseIndexError2(index_1, (*t_p0).data.len - 1);
        goto BeforeRet_;
      }
      (*t_p0).data.p->data[index_1].Field2 = val_p2;
    }
    goto LA6_;
  LA8_:;
    {
      NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;
      tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *T21_;
      NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;
      {
        NI T13_;
        NI correctSizeX60gensym21__1;
        T13_ = (*t_p0).data.len;
        if (!(T13_ == ((NI)0)))
          goto LA14_;
        correctSizeX60gensym21__1 =
            slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        (*t_p0).counter = ((NI)0);
        if ((correctSizeX60gensym21__1) < ((NI)0) ||
            (correctSizeX60gensym21__1) > ((NI)IL64(9223372036854775807))) {
          raiseRangeErrorI(correctSizeX60gensym21__1, ((NI)0),
                           ((NI)IL64(9223372036854775807)));
          goto BeforeRet_;
        }
        newSeq__w_u1405((&(*t_p0).data), (correctSizeX60gensym21__1));
      }
    LA14_:;
      {
        NIM_BOOL T18_;
        T18_ = (NIM_BOOL)0;
        T18_ = mustRehash__w_u2024((*t_p0));
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T18_)
          goto LA19_;
        enlarge__w_u2167(t_p0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        index_1 = rawGetKnownHC__w_u2612((*t_p0), key_p1, hc_1);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA19_:;
      if (nimSubInt(((NI)-1), index_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      index_1 = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13);
      T21_ = (tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *)0;
      T21_ = t_p0;
      rawInsert__w_u2455(T21_, (&(*t_p0).data), key_p1, val_p2, hc_1, index_1);
      if (NIM_UNLIKELY(*nimErr_))
        goto BeforeRet_;
      if (nimAddInt((*t_p0).counter, ((NI)1),
                    &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) {
        raiseOverflow();
        goto BeforeRet_;
      };
      (*t_p0).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14);
    }
  LA6_:;
  }
BeforeRet_:;
}
N_LIB_PRIVATE
N_NIMCALL(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng,
          toTable__w_u1365)(tyTuple__XOVT24GHXwqiEj5GCsEGCA *pairs_p0,
                            NI pairs_p0Len_0) {
  tyObject_Table__VXRlZVRc73Y2yFgFbVYXng result;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    nimZeroMem((void *)(&result),
               sizeof(tyObject_Table__VXRlZVRc73Y2yFgFbVYXng));
    result = initTable__w_u1391(pairs_p0Len_0);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    {
      NimStringV2 *key_1;
      NI *val_1;
      NI i_1;
      key_1 = (NimStringV2 *)0;
      val_1 = (NI *)0;
      i_1 = ((NI)0);
      {
        while (1) {
          NI colontmpD_;
          if (!(i_1 < pairs_p0Len_0))
            goto LA3;
          colontmpD_ = (NI)0;
          if (i_1 < 0 || i_1 >= pairs_p0Len_0) {
            raiseIndexError2(i_1, pairs_p0Len_0 - 1);
            goto BeforeRet_;
          }
          key_1 = (&pairs_p0[i_1].Field0);
          if (i_1 < 0 || i_1 >= pairs_p0Len_0) {
            raiseIndexError2(i_1, pairs_p0Len_0 - 1);
            goto BeforeRet_;
          }
          val_1 = (&pairs_p0[i_1].Field1);
          colontmpD_ = (*val_1);
          X5BX5Deq___w_u1637((&result), (*key_1), colontmpD_);
          if (NIM_UNLIKELY(*nimErr_))
            goto BeforeRet_;
          i_1 += ((NI)1);
        }
      LA3:;
      }
    }
  }
BeforeRet_:;
  return result;
}
static N_INLINE(NI,
                rawGet__w_u389)(tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw t_p0,
                                tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1,
                                NI *hc_p2) {
  NI result;
  NI T1_;
  NI h_1;
  NI T11_;
  NI TM__4SoG2KRQy3oMm9aUzSLtGrA_15;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = (NI)0;
    T1_ = (NI)0;
    T1_ = hash__w_u396(((key_p1).p) ? (key_p1.p->data) : NIM_NIL, key_p1.len);
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    (*hc_p2) = T1_;
    {
      if (!((*hc_p2) == ((NI)0)))
        goto LA4_;
      (*hc_p2) = ((NI)314159265);
    }
  LA4_:;
    {
      NI T8_;
      T8_ = t_p0.data.len;
      if (!(T8_ == ((NI)0)))
        goto LA9_;
      result = ((NI)-1);
      goto BeforeRet_;
    }
  LA9_:;
    T11_ = (t_p0.data.len - 1);
    h_1 = (NI)((*hc_p2) & T11_);
    {
      while (1) {
        NIM_BOOL T14_;
        NI T21_;
        if (h_1 < 0 || h_1 >= t_p0.data.len) {
          raiseIndexError2(h_1, t_p0.data.len - 1);
          goto BeforeRet_;
        }
        T14_ = (NIM_BOOL)0;
        T14_ = isFilled__pureZcollectionsZtables_u31(
            t_p0.data.p->data[h_1].Field0);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
        if (!T14_)
          goto LA13;
        {
          NIM_BOOL T17_;
          T17_ = (NIM_BOOL)0;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
          if (!(T17_))
            goto LA18_;
          if (h_1 < 0 || h_1 >= t_p0.data.len) {
            raiseIndexError2(h_1, t_p0.data.len - 1);
            goto BeforeRet_;
          }
          T17_ = eqeq___w_u598(t_p0.data.p->data[h_1].Field1, key_p1);
        LA18_:;
          if (!T17_)
            goto LA19_;
          result = h_1;
          goto BeforeRet_;
        }
      LA19_:;
        T21_ = (t_p0.data.len - 1);
        h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
        if (NIM_UNLIKELY(*nimErr_))
          goto BeforeRet_;
      }
    LA13:;
    }
    if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_15)) {
      raiseOverflow();
      goto BeforeRet_;
    };
    result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_15);
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(NI,
          getOrDefault__w_u375)(tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw t_p0,
                                tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1) {
  NI result;
  NI hcX60gensym1__1;
  NI indexX60gensym1__1;
  NIM_BOOL *nimErr_;
  {
    nimErr_ = nimErrorFlag();
    result = 0;
    hcX60gensym1__1 = (NI)0;
    indexX60gensym1__1 = rawGet__w_u389(t_p0, key_p1, (&hcX60gensym1__1));
    if (NIM_UNLIKELY(*nimErr_))
      goto BeforeRet_;
    {
      if (!(((NI)0) <= indexX60gensym1__1))
        goto LA3_;
      if (indexX60gensym1__1 < 0 || indexX60gensym1__1 >= t_p0.data.len) {
        raiseIndexError2(indexX60gensym1__1, t_p0.data.len - 1);
        goto BeforeRet_;
      }
      result = t_p0.data.p->data[indexX60gensym1__1].Field2;
    }
  LA3_:;
  }
BeforeRet_:;
  return result;
}
N_LIB_PRIVATE
N_NIMCALL(void,
          eqdestroy___w_u701)(tySequence__gTwrrlHWmZAujkkSb6c2Wg dest_p0) {
  NI colontmp_;
  colontmp_ = ((NI)0);
  {
    while (1) {
      NI T3_;
      T3_ = dest_p0.len;
      if (!(colontmp_ < T3_))
        goto LA2;
      eqdestroy___w_u42(dest_p0.p->data[colontmp_].Field1);
      colontmp_ += ((NI)1);
    }
  LA2:;
  }
  if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
    alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__PCiVg29bAs9cXcHeoQrt1xeA));
  }
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u899)(
    tyObject_Table__UF416iFSxkZL9c3cC1hNQ9aw *dest_p0) {
  eqdestroy___w_u701((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___w_u1529)(
    tyObject_Table__VXRlZVRc73Y2yFgFbVYXng *dest_p0) {
  eqdestroy___w_u1547((*dest_p0).data);
}
