/* Generated by Nim Compiler v2.2.5 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___6EqUI9bVt1CUoWlwB5HbmCA
    tyObject_TimezonecolonObjectType___6EqUI9bVt1CUoWlwB5HbmCA;
N_LIB_PRIVATE
    NIM_THREADVAR tyObject_TimezonecolonObjectType___6EqUI9bVt1CUoWlwB5HbmCA
        *utcInstance__pureZtimes_u2031;
N_LIB_PRIVATE
    NIM_THREADVAR tyObject_TimezonecolonObjectType___6EqUI9bVt1CUoWlwB5HbmCA
        *localInstance__pureZtimes_u2032;
